# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jbclements/sqlite-table"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.12.05
	GH_COMMIT="d1b892fe91a9413efd42da9ca75b5e1db5333993"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the sqlite-table Racket package"
HOMEPAGE="https://github.com/jbclements/sqlite-table"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
