# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/atomichron"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.05.31
	GH_COMMIT="77dddb12241a8d7ca8f1520a1862a79cad91a6c6"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A microbenchmarking library"
HOMEPAGE="https://github.com/jackfirth/atomichron"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rebellion
"
RDEPEND="${DEPEND}"
