# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mbutterick/pitfall"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.18
	GH_COMMIT="615d3830f03a3d38fe7d4d439391f1dcdaf2b597"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="PDF generation library [under development]"
HOMEPAGE="https://github.com/mbutterick/pitfall"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/debug
	dev-racket/gregor
	dev-racket/sugar
	dev-racket/fontland
	dev-racket/brag
	dev-racket/beautiful-racket-lib
	dev-racket/with-cache
"
RDEPEND="${DEPEND}"
