# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mordae/racket-libserialport"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.05.18
	GH_COMMIT="51f85372a6e51cc3268c4e45c0bef0f89c836b25"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="FFI bindings for the libserialport library."
HOMEPAGE="https://github.com/mordae/racket-libserialport"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/mordae
	dev-racket/misc1
"
RDEPEND="${DEPEND}"
