# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="DarrenN/identikon"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.07.13
	GH_COMMIT="d8908ee6955e69466270692599eb9076adc6a28b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Tiny framework for generating identicons"
HOMEPAGE="https://github.com/DarrenN/identikon"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/quickcheck
	dev-racket/css-tools
	dev-racket/sugar
"
RDEPEND="${DEPEND}"
