# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="tonyg/racket-struct-defaults"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="97fb427ab2210ba145486604b2095704c51da6a9"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Default values in struct ctors and patterns."
HOMEPAGE="https://github.com/tonyg/racket-struct-defaults"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
