# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="oetr/racket-plplot"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.03.16
	GH_COMMIT="fab8fe83993506b871eab9f1f6a7f2be3324c0dd"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="FFI bindings to PLplot"
HOMEPAGE="https://github.com/oetr/racket-plplot"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
