# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Bogdanp/racket-http-easy"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.03
	GH_COMMIT="d1c04a6a127864fd2ab77918bc524a33e357c038"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A high-level HTTP client."
HOMEPAGE="https://github.com/Bogdanp/racket-http-easy"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/resource-pool-lib
	dev-racket/memoize
"
RDEPEND="${DEPEND}"

S="${S}/http-easy"
