# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/inexact-number-lang"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.01.21
	GH_COMMIT="b7821d0871a698af4c3833a7f8e2b49e3625eb4a"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A lang-extension that reads every number as inexact"
HOMEPAGE="https://github.com/AlexKnauth/inexact-number-lang"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
