# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="rfindler/popl-2012-ryr-talk"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="9da05129de004cc1df0ccfbd821e8542a9155021"
	KEYWORDS="~amd64"
fi

RACKET_PN="popl-2012-ryr-talk"

inherit gh racket

DESCRIPTION="the popl-2012-ryr-talk Racket package"
HOMEPAGE="https://github.com/rfindler/popl-2012-ryr-talk"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
