# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jessealama/argo"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.04
	GH_COMMIT="ee49d60a8d73b32e8323a1324503f1d9c1022e5f"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Validate JSON data using JSON Schema."
HOMEPAGE="https://github.com/jessealama/argo"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/brag
	dev-racket/ejs
	dev-racket/uri-template
	dev-racket/json-pointer
	dev-racket/beautiful-racket-lib
	dev-racket/sugar
	dev-racket/http
"
RDEPEND="${DEPEND}"
