# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="david-christiansen/brush"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.11.09
	GH_COMMIT="91b83cda313f77f2068f0c02753c55c2563680d5"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A semi-literate programming package for Scribble"
HOMEPAGE="https://github.com/david-christiansen/brush"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
