# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="cjfuller/deferred"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="fccb728dc9cbc0a6acb38fd0bc782db41bf32d4c"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A simple library for deferring asynchronous tasks until a specified time"
HOMEPAGE="https://github.com/cjfuller/deferred"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
