# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="lwhjp/logo"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.02.03
	GH_COMMIT="2e9f3f7ffb4b8100aeb52943098f150c1cf7441a"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A #lang for Logo"
HOMEPAGE="https://github.com/lwhjp/logo"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
