# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="samth/parameter.plt"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="d084723e260a133e792317286fb05494aabc29ed"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Parameter utilities"
HOMEPAGE="https://github.com/samth/parameter.plt"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
