# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="simmsb/racket-cord"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.12
	GH_COMMIT="9416a45dc149330d5283786e4416a3d61aea4933"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Racket bindings for discord."
HOMEPAGE="https://github.com/simmsb/racket-cord"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rfc6455
	dev-racket/http-easy
"
RDEPEND="${DEPEND}"
