# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/match-string"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.25
	GH_COMMIT="ffc077653b3cdd851fd55589256f1e1177f6ed68"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="string-append and append as a match patterns"
HOMEPAGE="https://github.com/AlexKnauth/match-string"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/anaphoric
"
RDEPEND="${DEPEND}"
