# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/racket-disposable"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.10.28
	GH_COMMIT="843d3e224fd874b9c463b74cb5ef13d8a0b5766a"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Tests for the disposable package"
HOMEPAGE="https://github.com/jackfirth/racket-disposable"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/fixture
	dev-racket/doc-coverage
	dev-racket/disposable
"
RDEPEND="${DEPEND}"

S="${S}/disposable-test"
