# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jsmaniac/typed-struct-props"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.04
	GH_COMMIT="5512b7f4c9dff6b2be445435b86babfc9b189fc8"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the typed-struct-props Racket package"
HOMEPAGE="https://github.com/jsmaniac/typed-struct-props"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/type-expander
"
RDEPEND="${DEPEND}"
