# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jeapostrophe/superc/"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="929d3e32db7a5c69fa9e033db7b5707cff329672"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A language for writing C with Racket macros and an easy interface to Racket"
HOMEPAGE="https://github.com/jeapostrophe/superc/"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
