# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="git.sr.ht"
GH_REPO="~sschwarzer/sudoku-solver"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.11
	GH_COMMIT="bac722fc3de3f6b434c36587fd60d46162e95191"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Sudoku solver that can also show the solution process as a GraphViz dot file"
HOMEPAGE="https://git.sr.ht/~sschwarzer/sudoku-solver"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
