# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="herbie-fp/egg-herbie"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.12.08
	GH_COMMIT="edeee228439c6ffa5f24cc5b4cd23ddf1e2a0039"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An egg interface for Herbie."
HOMEPAGE="https://github.com/herbie-fp/egg-herbie"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/egg-herbie-linux
	dev-racket/egg-herbie-osx
	dev-racket/egg-herbie-windows
"
RDEPEND="${DEPEND}"
