# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="xgqt/scheme-counter"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.07.04
	GH_COMMIT="52c93e613b2b2ddf4a4e587d103e6c352d2cd6d2"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Small counter library to use for console output, logging, etc."
HOMEPAGE="https://gitlab.com/xgqt/scheme-counter"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
