# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mxork/raco-format"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.28
	GH_COMMIT="f91b375520fe05a008907be70fcd85cf02c0d574"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Format racket source files"
HOMEPAGE="https://github.com/mxork/raco-format"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/threading-lib
"
RDEPEND="${DEPEND}"
