# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="takikawa/racket-rsvg"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.05
	GH_COMMIT="9a9c82801e40622238794fdac556339ac0a6c912"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="FFI bindings to libRSVG, a library for loading SVG documents"
HOMEPAGE="https://github.com/takikawa/racket-rsvg"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
