# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="BourgondAries/memo"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.11.24
	GH_COMMIT="3ecfa4ad20c38ce97fedaed848d08348e92c56d3"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Memoization with finalizers and cleanup"
HOMEPAGE="https://github.com/BourgondAries/memo"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/thread-utils
	dev-racket/nested-hash
	dev-racket/finalizer
"
RDEPEND="${DEPEND}"
