# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="liberalartist/appveyor-racket"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.02.12
	GH_COMMIT="21f21d99160a0edefd7ceeb001210c88a8af1099"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Help for using AppVeyor with Racket projects"
HOMEPAGE="https://github.com/liberalartist/appveyor-racket"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
