# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Bogdanp/racket-country"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.09
	GH_COMMIT="7db381e159eed634a9b791eb350dea026c1a65de"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Facilities for working with country data."
HOMEPAGE="https://github.com/Bogdanp/racket-country"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

S="${S}/country"
