# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="zyrolasting/file-watchers"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.06.02
	GH_COMMIT="c1ac766a345a335438165ab0d13a4d8f6aec6162"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Sensible file watching procedures"
HOMEPAGE="https://github.com/zyrolasting/file-watchers"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
