# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="rfindler/lambdajam-2015-racket-pl-pl"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="4c9001dca9fb72c885d8cc1bef057ac8f56c24d0"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the lambdajam-2015-racket-pl-pl Racket package"
HOMEPAGE="https://github.com/rfindler/lambdajam-2015-racket-pl-pl"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/lang-slide
"
RDEPEND="${DEPEND}"
