# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dstorrs/file-metadata"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.09.11
	GH_COMMIT="d8f90fdd911e0e97b754cb74d5963f2c3c465637"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the file-metadata Racket package"
HOMEPAGE="https://github.com/dstorrs/file-metadata"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
