# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="schuster/asyncunit"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="ef9e5c45e83a6f44539d45c8ac52935a463a9659"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="RackUnit helper functions for asynchronous channels"
HOMEPAGE="https://github.com/schuster/asyncunit"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
