# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mbutterick/quad"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.19
	GH_COMMIT="9060de1330853dc206bbf57d75a1d261b7bc4816"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Document processor (unstable)"
HOMEPAGE="https://github.com/mbutterick/quad"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/words
	dev-racket/debug
	dev-racket/markdown
	dev-racket/txexpr
	dev-racket/sugar
	dev-racket/pollen
	dev-racket/pitfall
	dev-racket/hyphenate
	dev-racket/fontland
	dev-racket/beautiful-racket-lib
"
RDEPEND="${DEPEND}"
