# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Kalimehtar/hive-common"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.05.09
	GH_COMMIT="38d5bffacf8ddc6b8e0680997d23bf0502153bb7"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Hive: client-server framework. This is library for both client and server."
HOMEPAGE="https://github.com/Kalimehtar/hive-common"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/thread-utils
"
RDEPEND="${DEPEND}"
