# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jeapostrophe/rackunit-chk"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.09.04
	GH_COMMIT="62c80697d9e8c4a5f5b57832e3930313732836c4"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="a short hand for writing rackunit tests"
HOMEPAGE="https://github.com/jeapostrophe/rackunit-chk"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
