# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mordae/racket-avl"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.01.08
	GH_COMMIT="e981880a7d4c202368cdd74c94cf11cbac42a29e"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="AVL Trees for Racket"
HOMEPAGE="https://github.com/mordae/racket-avl"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
