# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="lexi-lambda/racket-vector-struct"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="f5137a445b567a213f20d9c35c60cea88f61c7b1"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A simple abstraction to use vectors like structs for performance"
HOMEPAGE="https://github.com/lexi-lambda/racket-vector-struct"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
