# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="oetr/racket-opencv"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="8124eb6b620769137656547e83f9d9587ab37c23"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="FFI bindings to the OpenCV library"
HOMEPAGE="https://github.com/oetr/racket-opencv"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
