# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="dustyweb/magenc"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.08
	GH_COMMIT="f5e011cb3f4fa060623764a4a80860e31ebca9fc"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Symmetric encryption for magnet URIs (code and docs)"
HOMEPAGE="https://gitlab.com/dustyweb/magenc"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/sql
	dev-racket/csexp
	dev-racket/crypto-lib
"
RDEPEND="${DEPEND}"

S="${S}/magenc"
