# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="racket-tw/reporter"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.09
	GH_COMMIT="2b1b2a23a08fc4b735cbd5c888d814d96b140d4e"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A util toolbox for compiler error reporting"
HOMEPAGE="https://github.com/racket-tw/reporter"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/c-utils
	dev-racket/ansi-color
"
RDEPEND="${DEPEND}"
