# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="renatoathaydes/ansi-color"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.11.20
	GH_COMMIT="20363d90fcef9219580ec0d6a78eea834df39d21"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the ansi-color Racket package"
HOMEPAGE="https://github.com/renatoathaydes/ansi-color"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
