# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="florence/reactor"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.12.29
	GH_COMMIT="c4687bd43fafcd09802042648900d4737b04f923"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An embedded synchronous reactive language, a la reactiveML"
HOMEPAGE="https://github.com/florence/reactor"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/seq-no-order
"
RDEPEND="${DEPEND}"
