# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Junker/response-ext"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.03.19
	GH_COMMIT="50c95a7799602079b6a77d5576832a8d91a4bbd5"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Extended HTTP response functions for Racket Web Server"
HOMEPAGE="https://github.com/Junker/response-ext"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
