# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="bennn/syntax-parse-example"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.10.19
	GH_COMMIT="2d06b1541888b94aa04a0d77aac9ebdd503ee90a"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Example macros written using syntax/parse"
HOMEPAGE="https://github.com/bennn/syntax-parse-example"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
