# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Metaxal/learn-to-type/"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.01.20
	GH_COMMIT="e92730f9e7c1560a9f1dc82fbed6046c4532d167"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A very simple GUI program to learn to type by copying a text."
HOMEPAGE="https://github.com/Metaxal/learn-to-type/"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
