# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="RayRacine/ibkre"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.23
	GH_COMMIT="9160c821fabe516739be0b4f06b3e5ad3c21fe7b"
	KEYWORDS="~amd64"
fi

RACKET_PN="Ibkre"

inherit gh racket

DESCRIPTION="IBK Actor/Syndicate Library"
HOMEPAGE="https://gitlab.com/RayRacine/ibkre"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/syndicate
	dev-racket/bitsyntax
	dev-racket/opt
"
RDEPEND="${DEPEND}"
