# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dedbox/racket-js-voxel"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.11.07
	GH_COMMIT="7a97d657b2d4729c1f79aa2fb52435eadff92650"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A general-purpose voxel programming environment"
HOMEPAGE="https://github.com/dedbox/racket-js-voxel"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rfc6455
	dev-racket/glm
"
RDEPEND="${DEPEND}"
