# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="BourgondAries/k-infix"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.11.24
	GH_COMMIT="07ed4c23905ea8b2b85a5f321d56ad038170766f"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the k-infix Racket package"
HOMEPAGE="https://github.com/BourgondAries/k-infix"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/memoize
"
RDEPEND="${DEPEND}"
