# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dvanhorn/fector"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="269812d67549fbd77273f5025a4144214d790081"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Persistent Functional Vectors"
HOMEPAGE="https://github.com/dvanhorn/fector"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
