# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jbclements/postmark"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="6204838d15c5de48389a2a45ee9158493cc76bc8"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A front-end for the Postmark email delivery service API"
HOMEPAGE="https://github.com/jbclements/postmark"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
