# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/set-exp"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.02.05
	GH_COMMIT="19c898f13278efee5399de7307fc95d0f53ee82d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Literal set syntax"
HOMEPAGE="https://github.com/jackfirth/set-exp"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/cover
	dev-racket/doc-coverage
"
RDEPEND="${DEPEND}"
