# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="BourgondAries/logger"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.08.18
	GH_COMMIT="a4cb492d14d2e65840818ed4fe169011b30be23a"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A simple logging library with color and 7 log levels."
HOMEPAGE="https://github.com/BourgondAries/logger"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
