# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Bogdanp/racket-sentry"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.22
	GH_COMMIT="87d708bd4fc56ad272708ffd63ed1e2f50393b26"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A Sentry SDK for Racket. (tests only)"
HOMEPAGE="https://github.com/Bogdanp/racket-sentry"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/threading-lib
	dev-racket/sentry-lib
	dev-racket/gregor-lib
"
RDEPEND="${DEPEND}"

S="${S}/sentry-test"
