# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mflatt/s3-sync"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.04.28
	GH_COMMIT="d2f9bd298df3f4368817ff6a18c6f23304e1ffa4"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Sync filesystem with an S3 bucket"
HOMEPAGE="https://github.com/mflatt/s3-sync"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/http
	dev-racket/aws
"
RDEPEND="${DEPEND}"
