# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="soegaard/infix"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.12.18
	GH_COMMIT="3f7998e509f201f78eb986de0f09e0542a429ad0"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Infix Expressions"
HOMEPAGE="https://github.com/soegaard/infix"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
