# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="alehed/rex"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.06.13
	GH_COMMIT="e3b41f706b4b72ea5f168b0f2a2600d77ee07ea0"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Language for deterministic finite state machines"
HOMEPAGE="https://github.com/alehed/rex"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/brag
	dev-racket/br-parser-tools-lib
"
RDEPEND="${DEPEND}"
