# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mflatt/pict-balloon2"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.07
	GH_COMMIT="e445c3649f0a17232e05727cedc42ff585bd20f7"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the pict-balloon2 Racket package"
HOMEPAGE="https://github.com/mflatt/pict-balloon2"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
