# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="rmculpepper/webapi"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="c1a172e360db667be49dcd81eba85f4a35b73a94"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Implementations of a few web APIs, including OAuth2, PicasaWeb, and Blogger."
HOMEPAGE="https://github.com/rmculpepper/webapi"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/sxml
"
RDEPEND="${DEPEND}"
