# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jeroanan/nproc"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.10.04
	GH_COMMIT="779fe7db83918a6ade7cf27f64d2fd5f9358f8bc"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A simple wrapper to num_processors in gnulib's nproc module"
HOMEPAGE="https://github.com/jeroanan/nproc"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
