# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dedbox/racket-template"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.03.26
	GH_COMMIT="7e8cd438cdc168b74b1a23721d3410be330de209"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Template Macros"
HOMEPAGE="https://github.com/dedbox/racket-template"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/debug-scopes
"
RDEPEND="${DEPEND}"
