# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="lassik/racket-database-url"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.07.04
	GH_COMMIT="1bc45817ab41171da41d39c0027367eda698c463"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Parse DATABASE_URL for use with the Racket db module"
HOMEPAGE="https://github.com/lassik/racket-database-url"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
