# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="pnwamk/fme"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="63075d432e7803b2822a78568306c29a6fde557c"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Fourier-Motzkin elimination for integer inequality satisfiability"
HOMEPAGE="https://github.com/pnwamk/fme"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
