# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jeapostrophe/bloggy/"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="d189325911f28fdfd9b8d7ae64225838d6400596"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A very simple Racket blog system"
HOMEPAGE="https://github.com/jeapostrophe/bloggy/"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
