# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="thinkmoore/drracket-cyberpunk"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="65d2ccc304b2f1d81423f78f9330a314497f8aae"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the drracket-cyberpunk Racket package"
HOMEPAGE="https://github.com/thinkmoore/drracket-cyberpunk"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
