# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mromyers/infix-syntax"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.09.25
	GH_COMMIT="8886395e31dc0b5d0db3a77a75255df15492806c"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Expansion-time parsing of infix expressions."
HOMEPAGE="https://github.com/mromyers/infix-syntax"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
