# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="simonhaines/packrat"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.06.28
	GH_COMMIT="b439a1d997df7bc6cf5d5c4f349355d84cb89e03"
	KEYWORDS="~amd64"
fi

RACKET_PN="Packrat"

inherit gh racket

DESCRIPTION="the Packrat Racket package"
HOMEPAGE="https://github.com/simonhaines/packrat"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
