# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="parnikkapore/rkt-libquiche"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.22
	GH_COMMIT="26aa3ade5feaa8819648c10057ca064c4ec64d85"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the libquiche Racket package"
HOMEPAGE="https://github.com/parnikkapore/rkt-libquiche"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/reprovide-lang-lib
"
RDEPEND="${DEPEND}"
