# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="oquijano/sse"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.08
	GH_COMMIT="a6858b7ca41a6ab482c170e6223dc8ac4c7f4eb2"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Server Sent Events for Racket"
HOMEPAGE="https://gitlab.com/oquijano/sse"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
