# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="lassik/racket-scrapyard"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.05.10
	GH_COMMIT="23b49c3562f3b8fea01886a219230fe37e2abf2d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Light helper for web scrapers. Caches and parses downloaded files."
HOMEPAGE="https://github.com/lassik/racket-scrapyard"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/txexpr
	dev-racket/sxml
"
RDEPEND="${DEPEND}"
