# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="simmone/racket-simple-barcode"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.02.12
	GH_COMMIT="4afa806ff27de8e2715b15904e1f3fcec2c7f136"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Barcode tool"
HOMEPAGE="https://github.com/simmone/racket-simple-barcode"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/simple-svg
"
RDEPEND="${DEPEND}"
