# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="bennn/gtp-plot"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.23
	GH_COMMIT="bea5d7347dd850423a6faaad219dadd70f487950"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Plots for gradual typing performance"
HOMEPAGE="https://github.com/bennn/gtp-plot"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rackunit-abbrevs
	dev-racket/gtp-util
	dev-racket/reprovide-lang
	dev-racket/scribble-abbrevs
"
RDEPEND="${DEPEND}"
