# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="racket/pkg-push"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.10.24
	GH_COMMIT="3fc18d8edb81b854ed98897bef925c73f68597ed"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the pkg-push Racket package"
HOMEPAGE="https://github.com/racket/pkg-push"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/http
	dev-racket/aws
"
RDEPEND="${DEPEND}"
