# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="bennn/racket-mutt"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.01.31
	GH_COMMIT="c691ba0ab5ab13aac0f5fe843f3582e6789ee9eb"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Racket API for the Mutt email client"
HOMEPAGE="https://github.com/bennn/racket-mutt"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rackunit-abbrevs
	dev-racket/make-log-interceptor
"
RDEPEND="${DEPEND}"
