# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/colon-kw"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.05.24
	GH_COMMIT="a338070d902753978a5a297c737845c013231ea7"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="a lang-extension for writing :kw for #:kw"
HOMEPAGE="https://github.com/AlexKnauth/colon-kw"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
