# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="tonyg/racket-rfc6455"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.07.14
	GH_COMMIT="abdf0099c6930986a4ea9f352b9fb34ba73afea5"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="RFC 6455 WebSockets support for Racket."
HOMEPAGE="https://github.com/tonyg/racket-rfc6455"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
