# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="envlang/racket"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.04
	GH_COMMIT="c45bfb25492a5fbedad50c7ad530d82bbbb43e3c"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Prototype of a proof-of-concept for a language with first-class environments."
HOMEPAGE="https://github.com/envlang/racket"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/hyper-literate
	dev-racket/polysemy
	dev-racket/reprovide-lang-lib
	dev-racket/phc-toolkit
"
RDEPEND="${DEPEND}"
