# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="williewillus/racket-rfc8949"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.23
	GH_COMMIT="fa0335296db25aa137da79d653b6cb9759c507c0"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Implementation of Concise Binary Object Representation (RFC 8949) for Racket."
HOMEPAGE="https://github.com/williewillus/racket-rfc8949"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
