# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="uwplse/herbie"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.07.22
	GH_COMMIT="cd03acd15d439869dfb902ddc25712e324e4c499"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A tool for automatically improving the accuracy of floating point expressions"
HOMEPAGE="https://github.com/uwplse/herbie"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/fpbench
	dev-racket/rival
	dev-racket/regraph
	dev-racket/egg-herbie-linux
	dev-racket/egg-herbie-osx
	dev-racket/egg-herbie-windows
"
RDEPEND="${DEPEND}"

S="${S}/src"
