# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="robertkleffner/wort"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.03.14
	GH_COMMIT="433130f0f6f1fa90d7ed21b857d03bce856656b0"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A tiny concatenative language with polymorphic type inference"
HOMEPAGE="https://github.com/robertkleffner/wort"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/br-parser-tools-lib
	dev-racket/beautiful-racket-lib
	dev-racket/beautiful-racket
	dev-racket/brag
"
RDEPEND="${DEPEND}"
