# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="rmculpepper/sql"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.02.04
	GH_COMMIT="7bb2872fb7850f67a7db3c9e017dfc9b61bd612e"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="an S-expression notation for SQL"
HOMEPAGE="https://github.com/rmculpepper/sql"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
