# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jeapostrophe/opencl/"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="f984050b0c02beb6df186d1d531c4a92a98df1a1"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A Racket interface to OpenCL using an FFI"
HOMEPAGE="https://github.com/jeapostrophe/opencl/"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/superc
"
RDEPEND="${DEPEND}"
