# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="sorawee/define-who"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.12.12
	GH_COMMIT="c77167fe7d5c2f3057cc80d9c201f9e888f02545"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An anaphoric macro that binds who to function name"
HOMEPAGE="https://github.com/sorawee/define-who"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
