# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="tyynetyyne/teachpacks"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.10.18
	GH_COMMIT="f82605dc2de7e6b6267fe2b2e6a6481a1ab33a35"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Racket Turtle for drawing turtle-graphics."
HOMEPAGE="https://github.com/tyynetyyne/teachpacks"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
