# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jbclements/midi-readwrite"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="92953cfef013e2c654e8f972b5d55f0da220fae4"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="simple functions to read MIDI (.mid) files"
HOMEPAGE="https://github.com/jbclements/midi-readwrite"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
