# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="racket-tw/sauron"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.23
	GH_COMMIT="752ab46a26d63e4206762d7e9014b59c22cdef71"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A DrRacket plugin to make it experience like an IDE"
HOMEPAGE="https://github.com/racket-tw/sauron"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
