# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="racket-tw/sauron"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.07.02
	GH_COMMIT="6262a8a5aba36c381634bdbb55d1e26888180fe4"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A DrRacket plugin to make it experience like an IDE"
HOMEPAGE="https://github.com/racket-tw/sauron"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/file-watchers
	dev-racket/from-template
"
RDEPEND="${DEPEND}"
