# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="lexi-lambda/racket-curly-fn"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="d64cd71d5b386be85f5979edae6f6b6469a4df86"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the curly-fn-lib Racket package"
HOMEPAGE="https://github.com/lexi-lambda/racket-curly-fn"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/namespaced-transformer-lib
"
RDEPEND="${DEPEND}"

S="${S}/curly-fn-lib"
