# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/resyntax"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.19
	GH_COMMIT="1ed5103ea780f8eae389ef4ec2ff5e876b011602"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An experimental refactoring tool built on top of syntax-parse."
HOMEPAGE="https://github.com/jackfirth/resyntax"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rebellion
	dev-racket/fancy-app
	dev-racket/brag-lib
	dev-racket/br-parser-tools-lib
"
RDEPEND="${DEPEND}"
