# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="rfindler/lindenmayer"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.03.02
	GH_COMMIT="2ef7b4535d8ae1eb7cc2e16e2b630c30a4b9a34d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the lindenmayer Racket package"
HOMEPAGE="https://github.com/rfindler/lindenmayer"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/pict3d
"
RDEPEND="${DEPEND}"
