# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Metaxal/towers"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.01.20
	GH_COMMIT="e1224228b5b5b514c7063b44810c1bdd5f8d5d14"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="The GUI client interface for the Towers game."
HOMEPAGE="https://github.com/Metaxal/towers"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/towers-lib
	dev-racket/bazaar
"
RDEPEND="${DEPEND}"

S="${S}/towers"
