# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="simmone/racket-pure-crypto"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.02.12
	GH_COMMIT="797f643b39c714b8d67e899f659a01dd676a69a1"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="a pure crypto implementation for racket"
HOMEPAGE="https://github.com/simmone/racket-pure-crypto"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/detail
"
RDEPEND="${DEPEND}"
