# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="bitbucket.org"
GH_REPO="jbclements/derp-3"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.15
	GH_COMMIT="b26498d7bc7ab09a17b799c0e295f8e514930ca4"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the derp-3 Racket package"
HOMEPAGE="https://bitbucket.org/jbclements/derp-3"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
