# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="adjkant/json-sourcery"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.07.28
	GH_COMMIT="b8f98e44a2c98266315f9c8f78156972f6bc649d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="library package for json-sourcery"
HOMEPAGE="https://github.com/adjkant/json-sourcery"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/syntax-classes
"
RDEPEND="${DEPEND}"

S="${S}/json-sourcery-lib"
