# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dstorrs/value-evt"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.01
	GH_COMMIT="10c3b0cc46f7fface88d2609c6de29ed5cea5767"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the value-evt Racket package"
HOMEPAGE="https://github.com/dstorrs/value-evt"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
