# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Bogdanp/racket-review"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.03.28
	GH_COMMIT="1068767539572ce34ac9f3afc59658e54a21ef00"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A surface-level linter for #lang racket modules."
HOMEPAGE="https://github.com/Bogdanp/racket-review"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
