# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="bengreenman/choose-out"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.08
	GH_COMMIT="1f95bbe28c3ae1f4bc1e2556a2e363ae344c1bfd"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Conditional provide (choose during expansion of importing module)"
HOMEPAGE="https://gitlab.com/bengreenman/choose-out"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/scribble-abbrevs
"
RDEPEND="${DEPEND}"
