# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="racket/readline-gpl"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.10.24
	GH_COMMIT="c885a4b49a2ac1b59a56d108a7ed0341b71bfd86"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Cause readline collection to use GNU's readline library."
HOMEPAGE="https://github.com/racket/readline-gpl"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
