# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/racket-mock"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.10.23
	GH_COMMIT="5e8e2a1dd125e5e437510c87dabf903d0ec25749"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="RackUnit checks for testing with mocks from the mock package"
HOMEPAGE="https://github.com/jackfirth/racket-mock"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/sweet-exp
	dev-racket/mock
"
RDEPEND="${DEPEND}"

S="${S}/mock-rackunit"
