# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="RayRacine/http11-server"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.08
	GH_COMMIT="f45e745600995225fb492adc86bc31597b6b9b3d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the http11-server Racket package"
HOMEPAGE="https://gitlab.com/RayRacine/http11-server"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/uri
	dev-racket/string-util
	dev-racket/http11
"
RDEPEND="${DEPEND}"
