# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jeapostrophe/racket-langserver"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.22
	GH_COMMIT="2a4b446b72c069f89078c63e774117542beac917"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Language Server Protocol implementation for Racket"
HOMEPAGE="https://github.com/jeapostrophe/racket-langserver"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/chk
"
RDEPEND="${DEPEND}"
