# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/reprovide-lang"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.07.16
	GH_COMMIT="49c4c867964ddff42c5c61fe8a7e814851ed8a0c"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="a #lang for reproviding modules"
HOMEPAGE="https://github.com/AlexKnauth/reprovide-lang"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/reprovide-lang-lib
"
RDEPEND="${DEPEND}"

S="${S}/reprovide-lang"
