# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="LeifAndersen/racket-sml"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.01.24
	GH_COMMIT="f7a03fdf124dff96a1fe2d7eadfd260a5824b1c5"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="S-Markup Language"
HOMEPAGE="https://github.com/LeifAndersen/racket-sml"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
