# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/compose-app"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="b1ca7838740c3cc84e392ea17f9e57f0595c111f"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the compose-app Racket package"
HOMEPAGE="https://github.com/jackfirth/compose-app"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/fancy-app
"
RDEPEND="${DEPEND}"
