# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Bogdanp/racket-gui-easy"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.27
	GH_COMMIT="ae64e3060104ec636987307b8f4a60fee830b6d6"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A declarative API on top of racket/gui. (implementation)"
HOMEPAGE="https://github.com/Bogdanp/racket-gui-easy"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

S="${S}/gui-easy-lib"
