# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mflatt/uu-cs5510"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="d6736f807b31f637e141ae97d28d65e8e10465aa"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Utah CS 5510 homework submission plugin for DrRacket"
HOMEPAGE="https://github.com/mflatt/uu-cs5510"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/plai-lazy
	dev-racket/plai-typed-s-exp-match
	dev-racket/plai-typed
"
RDEPEND="${DEPEND}"
