# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="rmculpepper/racket-zeromq"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.03.05
	GH_COMMIT="d45ee2bbc64582b22055eee20d0ef777d519a3b4"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Bindings for ZeroMQ"
HOMEPAGE="https://github.com/rmculpepper/racket-zeromq"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/zeromq-r-lib
"
RDEPEND="${DEPEND}"

S="${S}/zeromq-r"
