# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jeapostrophe/lux"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.02
	GH_COMMIT="23caa1996bde1a88e53ae0e1cf8d650e18dcbc24"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="brilliant interactive programs"
HOMEPAGE="https://github.com/jeapostrophe/lux"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
