# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="samth/match-count"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="99dc72c1dc254602d92d46f12552b95fab6f2ee5"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Instrumented match"
HOMEPAGE="https://github.com/samth/match-count"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
