# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/kw-make-struct"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.07.16
	GH_COMMIT="260803074a12bba911646dec8e26b26f674952b3"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Naming struct fields with keywords for constructing and matching"
HOMEPAGE="https://github.com/AlexKnauth/kw-make-struct"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/syntax-classes-lib
"
RDEPEND="${DEPEND}"

S="${S}/kw-make-struct-lib"
