# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jeapostrophe/ring-buffer"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.02.02
	GH_COMMIT="e93665407487ca0d31e1dadebc570371044f0c27"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An imperative overwriting ring buffer data structure"
HOMEPAGE="https://github.com/jeapostrophe/ring-buffer"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
