# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Bogdanp/racket-monotonic"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.10.22
	GH_COMMIT="4d2271f47d3c40e121afec4afc37de8adb4cf773"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Monotonic time for Racket."
HOMEPAGE="https://github.com/Bogdanp/racket-monotonic"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
