# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="thoughtstem/racket-processing"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.01.18
	GH_COMMIT="c4c51b528fa10fe69f89cc7b7c27bb3388ad11c7"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the racket-processing Racket package"
HOMEPAGE="https://github.com/thoughtstem/racket-processing"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/racket-to
"
RDEPEND="${DEPEND}"
