# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mordae/racket-tasks"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="2d2e1e096fec61da49531a86421d7e7eb4a9f3df"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Sugar for sync."
HOMEPAGE="https://github.com/mordae/racket-tasks"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
