# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="RayRacine/http11"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.08
	GH_COMMIT="5d9a2f182168c01ca366cdd45c7bcf78cf8037be"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="HTTP v1.1  low level protocol library in Typed Racket."
HOMEPAGE="https://gitlab.com/RayRacine/http11"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/string-util
	dev-racket/opt
	dev-racket/date
	dev-racket/uri
"
RDEPEND="${DEPEND}"
