# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Bogdanp/racket-north"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.10.22
	GH_COMMIT="08353f574489c65907a0dd15c4c1629e18d77027"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A database migration tool."
HOMEPAGE="https://github.com/Bogdanp/racket-north"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/gregor-lib
"
RDEPEND="${DEPEND}"

S="${S}/north"
