# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="nanopass/nanopass-framework-racket"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.24
	GH_COMMIT="deac3a4bf937e1217ec54c5439710712b227fc5a"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the nanopass Racket package"
HOMEPAGE="https://github.com/nanopass/nanopass-framework-racket"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
