# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dvanhorn/ralist"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.02.18
	GH_COMMIT="8f830a01463c547d2588671e76202cfe566a3fb1"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Purely Functional Random Access Lists"
HOMEPAGE="https://github.com/dvanhorn/ralist"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
