# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mordae/racket-xexpr-path"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="59f07164a5735441953c411a78d7dbe2f8ebcdc0"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="XML Expression Path Lookup"
HOMEPAGE="https://github.com/mordae/racket-xexpr-path"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
