# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.flux.utah.edu"
GH_REPO="xsmith/clotho"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.26
	GH_COMMIT="7cc309787f07286e3b1411346f4e85e4bec09098"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A library for enabling parametric randomness in Racket applications."
HOMEPAGE="https://gitlab.flux.utah.edu/xsmith/clotho"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/version-string-with-git-hash
"
RDEPEND="${DEPEND}"

S="${S}/clotho"
