# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/reconstruct-template"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.10.23
	GH_COMMIT="e3502153aeb64cbcf5809c7e89178eca54c76e34"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the reconstruct-template Racket package"
HOMEPAGE="https://github.com/AlexKnauth/reconstruct-template"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
