# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="yanyingwang/smtp"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.13
	GH_COMMIT="25e7804b665dab551fee134c2913edfd4f6ba9e1"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A practical library to send emails using SMTP protocol"
HOMEPAGE="https://github.com/yanyingwang/smtp"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/scribble-rainbow-delimiters
	dev-racket/uuid
	dev-racket/gregor-lib
"
RDEPEND="${DEPEND}"
