# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="takikawa/lipics-scribble"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.09.02
	GH_COMMIT="32a8cb9782493e237c25994f70aa7c572d7ea567"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Scribble languages for the LIPIcs paper format"
HOMEPAGE="https://github.com/takikawa/lipics-scribble"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/sha
"
RDEPEND="${DEPEND}"
