# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="lexi-lambda/alexis-collection-lens"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="4f91587e8a5728b02c1ea9af9ac7476baf39b928"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Deprecated. Use the collections-lens package instead."
HOMEPAGE="https://github.com/lexi-lambda/alexis-collection-lens"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/doc-coverage
	dev-racket/cover-coveralls
	dev-racket/cover
	dev-racket/lens
	dev-racket/curly-fn
	dev-racket/alexis-collections
"
RDEPEND="${DEPEND}"
