# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="oransimhony/drracket-ayu-mirage"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.05.06
	GH_COMMIT="5271740c3f0089e3958647353c24b73a3a80e401"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the drracket-ayu-mirage Racket package"
HOMEPAGE="https://github.com/oransimhony/drracket-ayu-mirage"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
