# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jiujiu1123/defensive-to-contracts"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.10.17
	GH_COMMIT="f64d8cb80a17fb981eb8269ef15f1fdb2f4d190b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the defensive-to-contracts Racket package"
HOMEPAGE="https://github.com/jiujiu1123/defensive-to-contracts"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
