# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Kalimehtar/multicolumn"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.11.08
	GH_COMMIT="916e9acca5ccf56b319bf5e641fac483ed60eac9"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the multicolumn Racket package"
HOMEPAGE="https://github.com/Kalimehtar/multicolumn"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/stretchable-snip
"
RDEPEND="${DEPEND}"
