# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dstorrs/racket-trie"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.10.16
	GH_COMMIT="da9564e8187ace2a4a891c979ef1e7f15a3d306e"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the trie Racket package"
HOMEPAGE="https://github.com/dstorrs/racket-trie"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/struct-plus-plus
	dev-racket/handy
"
RDEPEND="${DEPEND}"
