# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="tautologico/drracket-zenburn"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="baec7d09cf9dad88303f123d30626fc466b32c81"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="The Zenburn colorscheme for DrRacket."
HOMEPAGE="https://github.com/tautologico/drracket-zenburn"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
