# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="greghendershott/frog"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.02.16
	GH_COMMIT="93d8b442c2e619334612b7e2d091e4eb33995021"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Static blog generator application. Supports Twitter Bootstrap, Pygments, more."
HOMEPAGE="https://github.com/greghendershott/frog"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/threading-doc
	dev-racket/threading-lib
	dev-racket/reprovide-lang
	dev-racket/markdown
	dev-racket/find-parent-dir
"
RDEPEND="${DEPEND}"
