# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="RayRacine/csrmesh"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.08
	GH_COMMIT="d7cc04b2bbfd45c71bf086bf5075de9ccd81415f"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Implementation of the Bluetooth CSR Mesh protocol."
HOMEPAGE="https://gitlab.com/RayRacine/csrmesh"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/word
	dev-racket/bitsyntax
	dev-racket/crypto
"
RDEPEND="${DEPEND}"
