# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="quakehead/rsc3"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="a25985dab29ad951893cd7afa6d86a9371315871"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="The rsc3 SuperCollider client ported to Racket"
HOMEPAGE="https://github.com/quakehead/rsc3"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
