# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jessealama/json-pointer"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.03.27
	GH_COMMIT="73e97e426eff151ffd705059771c5c92f2da4697"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Parse, render, and evaluate JSON Pointers (RFC 6901)."
HOMEPAGE="https://github.com/jessealama/json-pointer"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/ejs
"
RDEPEND="${DEPEND}"
