# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="countvajhula/generator-util"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.22
	GH_COMMIT="bed2e5ee7c8c55c07f9119425e9615355816568a"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Utilities for working with generators"
HOMEPAGE="https://github.com/countvajhula/generator-util"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/collections-doc
	dev-racket/cover-coveralls
	dev-racket/cover
	dev-racket/scribble-abbrevs
	dev-racket/social-contract
	dev-racket/relation
	dev-racket/collections-lib
"
RDEPEND="${DEPEND}"
