# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="oldsin/bs"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.03.28
	GH_COMMIT="0a88ed7217076a6286fdaef0183bea596149991b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A Bitcoin Script Implementation for testing Script riddles."
HOMEPAGE="https://github.com/oldsin/bs"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/crypto-lib
	dev-racket/brag
"
RDEPEND="${DEPEND}"
