# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="lexi-lambda/racket-static-rename"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="50f1ff9866a3ef116471eb1a483c1992480dcd45"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the static-rename-doc Racket package"
HOMEPAGE="https://github.com/lexi-lambda/racket-static-rename"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/static-rename-lib
"
RDEPEND="${DEPEND}"

S="${S}/static-rename-doc"
