# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="massung/racket-csfml"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.02.13
	GH_COMMIT="7bcd88b848d054b5d847a51f65eb90988c260b81"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Bindings for CSFML 2.5 (https://www.sfml-dev.org/download/csfml/)"
HOMEPAGE="https://github.com/massung/racket-csfml"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
