# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/syntax-warn"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.12.07
	GH_COMMIT="f17fdd3179aeab8e5275a24e7d091d3ca42960a9"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="#lang racket/base/warn - Racket with syntax warnings"
HOMEPAGE="https://github.com/jackfirth/syntax-warn"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/syntax-warn-base
"
RDEPEND="${DEPEND}"

S="${S}/syntax-warn-lang"
