# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Kalimehtar/finalizer"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="74517770d70b786a3df48fd20ea9ea8059e4a641"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Trivial finalizer. Does action when object garbage collected"
HOMEPAGE="https://github.com/Kalimehtar/finalizer"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
