# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="simmone/racket-detail"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.02.12
	GH_COMMIT="5d4d2b765bfdfb0335c1a13a897a8bb3e65d85f9"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="detail used to reveal the details of the function"
HOMEPAGE="https://github.com/simmone/racket-detail"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
