# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="aymanosman/racket-intellij"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.22
	GH_COMMIT="22e52e0cc36472cd967e3e463f4d583cde0c2c0b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Support IntelliJ editor features"
HOMEPAGE="https://github.com/aymanosman/racket-intellij"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
