# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="racket/distro-build"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.28
	GH_COMMIT="1412e81854abbd26666f714acb49737ad2c5a963"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Tests for distro-build"
HOMEPAGE="https://github.com/racket/distro-build"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

S="${S}/distro-build-test"
