# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="racket/drdr"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.13
	GH_COMMIT="5a42b7a1cf77e42e7b6e6f439827d23af316b27a"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="DrDr, Racket's continuous integration system"
HOMEPAGE="https://github.com/racket/drdr"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/job-queue-lib
"
RDEPEND="${DEPEND}"
