# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/rebellion"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.27
	GH_COMMIT="fb9611c0087ef5a72b894436259a4be73b693f1e"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A collection of infrastructure libraries"
HOMEPAGE="https://github.com/jackfirth/rebellion"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
