# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Bogdanp/koyo-sentry"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.05.10
	GH_COMMIT="f04efd69d239347bc44cba1587deb1bc3d5ba8c7"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Integrates koyo and racket-sentry."
HOMEPAGE="https://github.com/Bogdanp/koyo-sentry"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/sentry-doc
	dev-racket/sentry-lib
	dev-racket/koyo-lib
"
RDEPEND="${DEPEND}"
