# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/measures-with-dimensions"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.07.18
	GH_COMMIT="fc6c78f79ac89cf488a5ccc5fc20391bd254886c"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="based on measures, but with dimensions and types"
HOMEPAGE="https://github.com/AlexKnauth/measures-with-dimensions"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/colon-match
	dev-racket/predicates
	dev-racket/reprovide-lang
	dev-racket/sweet-exp
	dev-racket/threading
"
RDEPEND="${DEPEND}"
