# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="otherjoel/beeswax"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.01
	GH_COMMIT="4d1377a69108357edfbdba844f954beffe1c05d4"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A Pollen-friendly template language"
HOMEPAGE="https://github.com/otherjoel/beeswax"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/sugar
	dev-racket/pollen
"
RDEPEND="${DEPEND}"
