# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="otherjoel/beeswax"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.07.03
	GH_COMMIT="3da19c8309722d506f57a329df572f20d0ddc391"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A Pollen-friendly template language"
HOMEPAGE="https://github.com/otherjoel/beeswax"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/sugar
	dev-racket/pollen
"
RDEPEND="${DEPEND}"
