# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jbclements/molis-hai"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.02.11
	GH_COMMIT="6a335ec73c144f9d8ac538752ca8e6fd0b3b3cce"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the molis-hai Racket package"
HOMEPAGE="https://github.com/jbclements/molis-hai"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/pfds
"
RDEPEND="${DEPEND}"
