# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="pnwamk/ddict"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.06.07
	GH_COMMIT="a322d6a38c203d946d48d3ae5892e9ad4f11bdf2"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Deterministic Dictionaries"
HOMEPAGE="https://github.com/pnwamk/ddict"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
