# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="aowens-21/drracket-custom-keybindings"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.27
	GH_COMMIT="ea5e6bcc52021624bf98615f2c447fc4d61a7ad4"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the drracket-custom-keybindings Racket package"
HOMEPAGE="https://github.com/aowens-21/drracket-custom-keybindings"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
