# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="johnstonskj/simple-oauth2"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.02.24
	GH_COMMIT="b8cb40511f64dcb274e17957e6fc9ab4c8a6cbea"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Simple OAuth 2.0 client implementation"
HOMEPAGE="https://github.com/johnstonskj/simple-oauth2"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/cover-coveralls
	dev-racket/rackunit-spec
	dev-racket/threading
	dev-racket/net-jwt
	dev-racket/dali
	dev-racket/crypto-lib
"
RDEPEND="${DEPEND}"
