# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="countvajhula/lazytree"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.22
	GH_COMMIT="3ca5ffaab10e763861a30bcaf5d8e147f68cb912"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Lightweight, general-purpose utilities for working with tree-structured data."
HOMEPAGE="https://github.com/countvajhula/lazytree"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/cover-coveralls
	dev-racket/cover
	dev-racket/functional-doc
	dev-racket/collections-doc
	dev-racket/scribble-abbrevs
	dev-racket/social-contract
	dev-racket/relation
	dev-racket/collections-lib
"
RDEPEND="${DEPEND}"
