# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/command-line-ext"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.06.03
	GH_COMMIT="e980b3b31d7a0cb6e0339335bde860f35a0fe471"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Extensible form of command-line with command-line-flag-expanders"
HOMEPAGE="https://github.com/jackfirth/command-line-ext"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/lens
	dev-racket/reprovide-lang
	dev-racket/generic-syntax-expanders
	dev-racket/fancy-app
"
RDEPEND="${DEPEND}"
