# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="bbusching/drrackgit"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.12.21
	GH_COMMIT="7c2836bf5a08858eca7d32959d8ae3fd90a5defe"
	KEYWORDS="~amd64"
fi

RACKET_PN="Drrackgit"

inherit gh racket

DESCRIPTION="A git plugin for DrRacket."
HOMEPAGE="https://github.com/bbusching/drrackgit"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/libgit2
"
RDEPEND="${DEPEND}"
