# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="philnguyen/intern"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.03.13
	GH_COMMIT="e2b46f803fe9d83368bde168fca8559f1210cfe3"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Type-safe interning of datatype in Typed Racket as a new sub-type of Index"
HOMEPAGE="https://github.com/philnguyen/intern"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

S="${S}/intern"
