# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="soegaard/urlang"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.09.29
	GH_COMMIT="086622e2306e72731016c7108aca3328e5082aee"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the urlang Racket package"
HOMEPAGE="https://github.com/soegaard/urlang"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/nanopass
"
RDEPEND="${DEPEND}"
