# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="berry-cs/sinbad-rkt"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.01.30
	GH_COMMIT="44b3e0881514bbfb7cc91780262968748b9f92eb"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the sinbad Racket package"
HOMEPAGE="https://github.com/berry-cs/sinbad-rkt"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/sxml
"
RDEPEND="${DEPEND}"

S="${S}/sinbad"
