# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="bennn/require-typed-check"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.04.17
	GH_COMMIT="7e8777a8576a74084c577b82dafaa759fe5ddfa8"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="require/typed, but skips contracts on already-typed imports"
HOMEPAGE="https://github.com/bennn/require-typed-check"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
