# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mflatt/pict3d-die-cut"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="29354f8dd2e9f964da834903332318a995d15727"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="For Pict3D, generates text and other 2-D shapes from paths"
HOMEPAGE="https://github.com/mflatt/pict3d-die-cut"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/glu-tessellate
	dev-racket/pict3d
"
RDEPEND="${DEPEND}"
