# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="racket/raco-cross"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.07.03
	GH_COMMIT="8660f85a7ddecaaf3042683f96bc1656f98189ea"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="documentation part of raco-cross"
HOMEPAGE="https://github.com/racket/raco-cross"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/raco-cross-lib
"
RDEPEND="${DEPEND}"

S="${S}/raco-cross-doc"
