# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mfelleisen/string-sexpr"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="b87319d3c34be048df24222e54c7dc4327063dc8"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="a supplementary package for Fundamentals I"
HOMEPAGE="https://github.com/mfelleisen/string-sexpr"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
