# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="bitbucket.org"
GH_REPO="derend/simple-matrix"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.15
	GH_COMMIT="19814fd5de10d42eea207939169ee5100e38c500"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A very simple library for basic matrix arithmetic."
HOMEPAGE="https://bitbucket.org/derend/simple-matrix"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
