# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Metaxal/quickscript-test"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.17
	GH_COMMIT="01bc23b78e87796a00f65eb70924133dd6ddc93e"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Tests for the quickscript package"
HOMEPAGE="https://github.com/Metaxal/quickscript-test"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
