# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="thoughtstem/image-coloring"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.01.23
	GH_COMMIT="1cd39f2ccacb2d6f12b577184e5b04f775a7bc4d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="For doing bitmap operations on 2htdp/image objects"
HOMEPAGE="https://github.com/thoughtstem/image-coloring"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
