# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/syntax-sloc"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.29
	GH_COMMIT="ea9bfa06a207ba63b481dcc794c55475eb6bcc33"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="counts the number of source lines of code in a racket syntax object"
HOMEPAGE="https://github.com/AlexKnauth/syntax-sloc"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/scribble-code-examples
	dev-racket/lang-file
"
RDEPEND="${DEPEND}"
