# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Kalimehtar/binary-class"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="69705ed306be38c9e4dd67d9075ec160ecdb82a4"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Classes for writing and reading binary data"
HOMEPAGE="https://github.com/Kalimehtar/binary-class"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
