# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="c2d7fa/rackunit-fancy-runner"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.11.19
	GH_COMMIT="c367fa93ed8a2daad4aa12cc9e947661d169dab6"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Command-line RackUnit test runner with fancy output"
HOMEPAGE="https://github.com/c2d7fa/rackunit-fancy-runner"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
