# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="david-christiansen/racket-zippers"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="ab11342e1359b0844f8f19f801cdd02d697f7ec3"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Utilities for working with and deriving Huet-style zippers"
HOMEPAGE="https://github.com/david-christiansen/racket-zippers"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
