# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="whichxjy/emoji"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.10.14
	GH_COMMIT="f1a1bececc0f6ed232bc3f77f1975818b457d9f8"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Emoji terminal output for Racket"
HOMEPAGE="https://github.com/whichxjy/emoji"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

S="${S}/emoji"
