# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="joseildofilho/Agatha-Lang"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.04.13
	GH_COMMIT="de9e340b97dbb22677dc3ba74d6ec8826bf9af90"
	KEYWORDS="~amd64"
fi

RACKET_PN="Agatha"

inherit gh racket

DESCRIPTION="Uma linguagem para Logica de primeira ordem"
HOMEPAGE="https://github.com/joseildofilho/Agatha-Lang"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/brag-lib
	dev-racket/beautiful-racket-lib
"
RDEPEND="${DEPEND}"
