# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/regex-machine"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.02.05
	GH_COMMIT="25754a4dc2aae351e2fe5db1b98101abb9ce088e"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An implementation of Russ Cox's regular expression machine language"
HOMEPAGE="https://github.com/jackfirth/regex-machine"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/reprovide-lang
"
RDEPEND="${DEPEND}"
