# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/type-conventions"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="550d9045206bd1c0a05713fa866a9cc2a0b48d99"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Forms for giving specific argument names implicit types"
HOMEPAGE="https://github.com/jackfirth/type-conventions"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
