# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="lexi-lambda/functional"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.07.02
	GH_COMMIT="be2285cd3da0e2fffe651a8ab723185bb669425d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the functional-doc Racket package"
HOMEPAGE="https://github.com/lexi-lambda/functional"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/functional-lib
	dev-racket/collections-lib
	dev-racket/collections-doc
"
RDEPEND="${DEPEND}"

S="${S}/functional-doc"
