# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jsmaniac/multi-id"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.04
	GH_COMMIT="6dbea1523d75a353b56d1bb63fbc15535d57f240"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the multi-id Racket package"
HOMEPAGE="https://github.com/jsmaniac/multi-id"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/scribble-enhanced
	dev-racket/hyper-literate
	dev-racket/type-expander
	dev-racket/phc-toolkit
"
RDEPEND="${DEPEND}"
