# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="rmculpepper/racket-hash-view"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.02.02
	GH_COMMIT="7bfad3b89241beaca45f43ec1d70ef3ed268b495"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Struct-like view for hashes"
HOMEPAGE="https://github.com/rmculpepper/racket-hash-view"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/hash-view-lib
"
RDEPEND="${DEPEND}"

S="${S}/hash-view"
