# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="zyrolasting/mind-map"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.06.19
	GH_COMMIT="8401400f1dbc7956357cd27563b6926f4e429d7c"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Write and render mind maps in Racket."
HOMEPAGE="https://github.com/zyrolasting/mind-map"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/racket-graphviz
"
RDEPEND="${DEPEND}"
