# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/compact-annotations"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="dcd5f87dec21f40904e92eefb747472151bd3ace"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Function type annotation syntax for Typed Racket similar to Haskell"
HOMEPAGE="https://github.com/jackfirth/compact-annotations"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/cover
"
RDEPEND="${DEPEND}"
