# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="rmculpepper/custom-load"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="4e70205c29ab0672663fcae78ded32563f01414b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A load handler that avoids stale zo files."
HOMEPAGE="https://github.com/rmculpepper/custom-load"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
