# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="thoughtstem/define-assets-from"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.01.07
	GH_COMMIT="f41954f7d955fdabbd697976d73344a5aa733d31"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the define-assets-from Racket package"
HOMEPAGE="https://github.com/thoughtstem/define-assets-from"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
