# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="RenaissanceBug/racket-jwt"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.12.04
	GH_COMMIT="0f747569e878ef14d1f5d2de527efd02af88fcf9"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="JSON Web Token / JSON Web Signature codec, verification, signing"
HOMEPAGE="https://github.com/RenaissanceBug/racket-jwt"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/option-bind
	dev-racket/crypto
	dev-racket/sha
"
RDEPEND="${DEPEND}"
