# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mordae/racket-esc-vp21"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="01bc89268f4f051d55885f64d4a0fac671a762b9"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Epson ESC/VP21 Projector Control"
HOMEPAGE="https://github.com/mordae/racket-esc-vp21"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/mordae
"
RDEPEND="${DEPEND}"
