# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jeapostrophe/restore"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="c38049acd1bde962453977d2469cf2ae8b99acb7"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="protocol for restore program state"
HOMEPAGE="https://github.com/jeapostrophe/restore"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
