# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="thoughtstem/happy-names"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.06.15
	GH_COMMIT="3a74d689059e77106318b751e65b113233008d19"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Simple generator for Heroku-like names (random adj + random noun)"
HOMEPAGE="https://github.com/thoughtstem/happy-names"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/memoize
"
RDEPEND="${DEPEND}"
