# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jsmaniac/extensible-parser-specifications"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.04
	GH_COMMIT="616130a74b83cf7790257150655949698a7a3913"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the extensible-parser-specifications Racket package"
HOMEPAGE="https://github.com/jsmaniac/extensible-parser-specifications"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/seq-no-order
	dev-racket/alexis-util
	dev-racket/generic-syntax-expanders
	dev-racket/phc-toolkit
"
RDEPEND="${DEPEND}"
