# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jeapostrophe/planet2-example"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="9d9e4dc77adfc7299987a4cbbe8ce43869eec53e"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An example package for testing purposes"
HOMEPAGE="https://github.com/jeapostrophe/planet2-example"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
