# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mflatt/slideshow-repl"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.08.22
	GH_COMMIT="e8d3f8fb08322cd1aa9553c1c0079d7bebb3e823"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the slideshow-repl Racket package"
HOMEPAGE="https://github.com/mflatt/slideshow-repl"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
