# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="willghatch/racket-extenor"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.01.14
	GH_COMMIT="6be463cb23ceca3b602ce1c482cd6d37cd7a6e15"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the extenor Racket package"
HOMEPAGE="https://github.com/willghatch/racket-extenor"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
