# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="APOS80/pmap"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="e352de9bbc6735b1ca089a21490f87fc2fba5279"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Implementations of map using parallel futures and places"
HOMEPAGE="https://github.com/APOS80/pmap"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
