# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="RayRacine/date"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.08
	GH_COMMIT="57d7adbbc09dffc26337bff1b1a3597c872be8ea"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the date Racket package"
HOMEPAGE="https://gitlab.com/RayRacine/date"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
