# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="lexi-lambda/rackunit-spec"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="96f9f48b2f4b004fafc67a3d26805983274568c4"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="BDD test helpers for rackunit"
HOMEPAGE="https://github.com/lexi-lambda/rackunit-spec"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
