# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="tonyg/racket-bitsyntax"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.12
	GH_COMMIT="fffe0d44e6183d19b5e2b22bf07be4192994243b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Erlang-like binary pattern-matching and bit string manipulation for Racket."
HOMEPAGE="https://github.com/tonyg/racket-bitsyntax"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
