# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="samth/git-slice"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.05.21
	GH_COMMIT="110b361425280e61abf8de99e5d41865afc5cddb"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="For slicing git repositories into pieces"
HOMEPAGE="https://github.com/samth/git-slice"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
