# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="florence/cover-codecov"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.02.26
	GH_COMMIT="b1a9de60da3c33894ddd6fcc3e26e8e6b614f708"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the cover-codecov Racket package"
HOMEPAGE="https://github.com/florence/cover-codecov"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/cover-lib
"
RDEPEND="${DEPEND}"
