# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="florence/datacell"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.03.21
	GH_COMMIT="fe91d9251542df5f9edb41fb457fb6c7f548d425"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A simple embedded dataflow language"
HOMEPAGE="https://github.com/florence/datacell"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
