# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="deepmind/deepmind-research"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.18
	GH_COMMIT="fa8c9be4bb0cfd0b8492203eb2a9f31ef995633c"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the satore Racket package"
HOMEPAGE="https://github.com/deepmind/deepmind-research"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/text-table
	dev-racket/global
	dev-racket/define2
	dev-racket/bazaar
"
RDEPEND="${DEPEND}"

S="${S}/satore"
