# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="stephanh42/RacketGL"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.12.19
	GH_COMMIT="1aaf2b2836680f807fbec5234ed475585b41b4ab"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Exhaustive Racket bindings to OpenGL"
HOMEPAGE="https://github.com/stephanh42/RacketGL"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
