# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/racket-ease"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="3a7149ded68be348611e346742feac85fca6d74f"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Library for easing things between start and stop values fluidly"
HOMEPAGE="https://github.com/jackfirth/racket-ease"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/doc-coverage
	dev-racket/cover
	dev-racket/fancy-app
	dev-racket/lens
	dev-racket/sweet-exp
"
RDEPEND="${DEPEND}"
