# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="samth/github.rkt"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="3dcabdece43c6f46050966a51ad237c75032cd17"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Github Bindings"
HOMEPAGE="https://github.com/samth/github.rkt"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
