# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/racket-request"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.05.30
	GH_COMMIT="fa78b05f5f063e767bcdb38a3d46cb4ff911ed56"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the request Racket package"
HOMEPAGE="https://github.com/jackfirth/racket-request"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/fancy-app
"
RDEPEND="${DEPEND}"
