# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mflatt/glu-tessellate"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="8efe65b35a2554be6dc613c016791ef2bf5ffb82"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the glu-tessellate Racket package"
HOMEPAGE="https://github.com/mflatt/glu-tessellate"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
