# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="sorawee/shlex"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.12.12
	GH_COMMIT="f469d9aee8bdba095d7147928223dd9e98d4dbdc"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="shlex for Racket: Simple lexical analysis"
HOMEPAGE="https://github.com/sorawee/shlex"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
