# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="nihirash/holy"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.11.02
	GH_COMMIT="e6574beb88937357cb73e834dacf10ceb1805495"
	KEYWORDS="~amd64"
fi

RACKET_PN="HoLy"

inherit gh racket

DESCRIPTION="the HoLy Racket package"
HOMEPAGE="https://github.com/nihirash/holy"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
