# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jsmaniac/scope-operations"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.04
	GH_COMMIT="5ea8f32528bcf1ed4393cf9a054920936c27a556"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the scope-operations Racket package"
HOMEPAGE="https://github.com/jsmaniac/scope-operations"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
