# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="arvyy/racket-raylib-2d"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.06.29
	GH_COMMIT="2f0b05f37e6bd81cf4246116c7d32f2744dc53c0"
	KEYWORDS="~amd64"
fi

RACKET_PN="racket-raylib-2d"

inherit gh racket

DESCRIPTION="Racket wrapper for Raylib (https://www.raylib.com/) v2.5 2D functionality"
HOMEPAGE="https://github.com/arvyy/racket-raylib-2d"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
