# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="alex-hhh/al2-test-runner"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.08.28
	GH_COMMIT="b6757271932151dff6507ee6f1b690d0268da808"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Alternative way of running rackunit tests"
HOMEPAGE="https://github.com/alex-hhh/al2-test-runner"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
