# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jeapostrophe/dos"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.06.01
	GH_COMMIT="e39826f5f65f7d0b849e5286859e70a62a985be1"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Delimited-continuation-based Operating-system Simulator"
HOMEPAGE="https://github.com/jeapostrophe/dos"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
