# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="bennn/gtp-paper"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.02.03
	GH_COMMIT="fe8ecf5bff7a89d80ad54e6f5a3a05281b65efee"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Quick-start for SIGPLAN Scribble papers"
HOMEPAGE="https://github.com/bennn/gtp-paper"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/scribble-abbrevs
"
RDEPEND="${DEPEND}"
