# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="spencereir/treap"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2016.10.09
	GH_COMMIT="e703ae7f1bec7a7131eeb2e9e5e6b488c4b45d7e"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Balanced binary search trees implemented through treaps"
HOMEPAGE="https://github.com/spencereir/treap"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
