# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="greghendershott/markdown"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.03.25
	GH_COMMIT="fc03a2728b12006b21c90b6c480cfe6ae91a4cbe"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Markdown format parser."
HOMEPAGE="https://github.com/greghendershott/markdown"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/sexp-diff-lib
	dev-racket/threading-lib
	dev-racket/parsack
"
RDEPEND="${DEPEND}"
