# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="camoy/stream-etc"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.09
	GH_COMMIT="637ad0b07259ce418e6f0aab06d34cd2ec8521cf"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Miscellaneous stream operations."
HOMEPAGE="https://github.com/camoy/stream-etc"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/threading-doc
	dev-racket/chk-lib
"
RDEPEND="${DEPEND}"
