# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="pleiad/play"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.06.18
	GH_COMMIT="34a145ffb815110bec33a48004e8897e48d11f51"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the play Racket package"
HOMEPAGE="https://github.com/pleiad/play"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
