# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jeapostrophe/c"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="c2efa315c13e420e6cf77ba8d5ce1f7eb9dbdc2c"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A language level for writing C code in DrRacket."
HOMEPAGE="https://github.com/jeapostrophe/c"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
