# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="leafac/extensible-functions"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.05.09
	GH_COMMIT="7aa4c134ba48137bd66d30ad9282d261a5507dbe"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A solution to the expression problem in Typed Racket"
HOMEPAGE="https://github.com/leafac/extensible-functions"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
