# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="cmpitg/racket-raw-string"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="b2745daf6da26c58b0138ab3ec0c20c1133e0ab6"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Raw string support without at-exp"
HOMEPAGE="https://github.com/cmpitg/racket-raw-string"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
