# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="MatrixForChange/files-viewer"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.05
	GH_COMMIT="164d4034611a970b5eb36ae20675241f0b52e82b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="a file manager for drracket"
HOMEPAGE="https://github.com/MatrixForChange/files-viewer"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
