# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="brown131/racquel"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.24
	GH_COMMIT="e5ae8cf5a848be390596122cd43f777efa683549"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Racquel is an object/relational mapper for Racket."
HOMEPAGE="https://github.com/brown131/racquel"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
