# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mflatt/sirmail"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.11
	GH_COMMIT="30c9bd6c6993ddd432d50a7ab705afa22ec34891"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An IMAP mail client"
HOMEPAGE="https://github.com/mflatt/sirmail"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
