# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="DarrenN/simple-http"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.06.13
	GH_COMMIT="cf15bfd0c71f3dd3189417dd1a7a34fc6bfad557"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Very small lib for making HTTP requests, usually to APIs."
HOMEPAGE="https://github.com/DarrenN/simple-http"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
