# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dzoep/futures-sort"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.01.01
	GH_COMMIT="dc1914f60b192897855989d4b87846eaa95aa777"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the futures-sort Racket package"
HOMEPAGE="https://github.com/dzoep/futures-sort"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/scribble-math
"
RDEPEND="${DEPEND}"
