# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="cwearl/fulmar"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="4cf60699558b3bb28fa813443456993d1563bfb2"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Generate C++ code from S-expressions"
HOMEPAGE="https://github.com/cwearl/fulmar"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
