# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Kalimehtar/gls"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.07.23
	GH_COMMIT="82f2f504a3ccf534126020baedb406f813863143"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the gls Racket package"
HOMEPAGE="https://github.com/Kalimehtar/gls"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
