# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="yanyingwang/http-client"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.25
	GH_COMMIT="2258e8e3275fe2f3be796fa4e8340b74ab3eeafa"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A practical http client library for sending data to http servers."
HOMEPAGE="https://github.com/yanyingwang/http-client"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/scribble-rainbow-delimiters
"
RDEPEND="${DEPEND}"
