# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="LiberalArtist/_-exp"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.28
	GH_COMMIT="7bc80bb0137c92effc29f5d01bbc6a14034712eb"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the _-exp Racket package"
HOMEPAGE="https://github.com/LiberalArtist/_-exp"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/adjutor
"
RDEPEND="${DEPEND}"
