# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/generic-syntax-expanders"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="6d3b41875095d0f18d6e1d88bf7a8ed3981fe999"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the generic-syntax-expanders Racket package"
HOMEPAGE="https://github.com/jackfirth/generic-syntax-expanders"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/predicates
	dev-racket/point-free
	dev-racket/lens
	dev-racket/reprovide-lang
	dev-racket/fancy-app
"
RDEPEND="${DEPEND}"
