# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="philnguyen/set-extras"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.05.06
	GH_COMMIT="7feeb7a3a6b05c2e9ce39a0ff31eae25e150119d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the set-extras Racket package"
HOMEPAGE="https://github.com/philnguyen/set-extras"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

S="${S}/set-extras"
