# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/mutable-match-lambda"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.10.01
	GH_COMMIT="28ea2c1f4e7a92826308c937608d4d91f2ead051"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the mutable-match-lambda Racket package"
HOMEPAGE="https://github.com/AlexKnauth/mutable-match-lambda"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/kw-utils
"
RDEPEND="${DEPEND}"
