# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/my-object"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="5a6ee970bad2ab86d2d69e1dbf2f7bb158e88963"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="my version of objects, inspired by things from heresy"
HOMEPAGE="https://github.com/AlexKnauth/my-object"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/heresy
	dev-racket/kw-utils
	dev-racket/hash-lambda
	dev-racket/lens
"
RDEPEND="${DEPEND}"
