# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="caisah/s-lib"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="de6ae621d8ffd670fede37f51212c8cb5a84bcf3"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A collection of functions for string & word manipulation"
HOMEPAGE="https://github.com/caisah/s-lib"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
