# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="samth/c.rkt/"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.12.18
	GH_COMMIT="a7087828d18fee7268c51104783279d285076560"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Utilities for manipulating C source code."
HOMEPAGE="https://github.com/samth/c.rkt/"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/abnf
"
RDEPEND="${DEPEND}"
