# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="johnstonskj/racket-scaffold"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.10.19
	GH_COMMIT="8613daf76e46fbf320de1230565e67de17fb92f5"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Simple templated content generator integrated with raco"
HOMEPAGE="https://github.com/johnstonskj/racket-scaffold"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/cover-coveralls
	dev-racket/dali
"
RDEPEND="${DEPEND}"
