# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="lehitoskin/libopenal-racket"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.12.20
	GH_COMMIT="30ce8d3f2e225b65d0502a0c4feb75e1dea35cc6"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Racket wrapper for the OpenAL library"
HOMEPAGE="https://github.com/lehitoskin/libopenal-racket"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
