# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="simmone/racket-simple-xlsx"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.12.13
	GH_COMMIT="4db2b2eb3e66f1bbc4c8cfff268697085891a9bc"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Xlsx File tool"
HOMEPAGE="https://github.com/simmone/racket-simple-xlsx"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
