# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="yanyingwang/colorize"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.05.04
	GH_COMMIT="157878ae018b5b6aebeb5e5e51d73ca38af4ad08"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="colorize your console"
HOMEPAGE="https://github.com/yanyingwang/colorize"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
