# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="sorawee/errortrace-pkg"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.12.12
	GH_COMMIT="cb7038eb6b7200ed44b75d45bbab66bb836232ec"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Errortrace installed packages"
HOMEPAGE="https://github.com/sorawee/errortrace-pkg"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/custom-load
"
RDEPEND="${DEPEND}"
