# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.flux.utah.edu"
GH_REPO="xsmith/xsmith"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.26
	GH_COMMIT="b5401707e5e225ac8f57e15843ffb8459a382235"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Generator of highly effective fuzz testers."
HOMEPAGE="https://gitlab.flux.utah.edu/xsmith/xsmith"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/memoize
	dev-racket/clotho
	dev-racket/racr
	dev-racket/pprint
"
RDEPEND="${DEPEND}"

S="${S}/xsmith"
