# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="camoy/redex-etc"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.11
	GH_COMMIT="c4583466d174ccbcb1adab3c3ed85342d7d67d9c"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Miscellanea for Redex."
HOMEPAGE="https://github.com/camoy/redex-etc"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/chk-lib
	dev-racket/private-in
	dev-racket/latex-utils
"
RDEPEND="${DEPEND}"
