# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="alex-hhh/gui-widget-mixins"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.23
	GH_COMMIT="81f02a227337afcaff434d4c4a5846dcee098b78"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Tool tips, cue text and validation for text-field% GUI widgets in Racket"
HOMEPAGE="https://github.com/alex-hhh/gui-widget-mixins"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
