# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/racket-retry"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.12.05
	GH_COMMIT="2a6ba58ab5f14707305e75063c3ee4519fc6dc7d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Composable configurable retryers for flakily failing operations."
HOMEPAGE="https://github.com/jackfirth/racket-retry"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/mock-rackunit
	dev-racket/gregor-doc
	dev-racket/mock
	dev-racket/reprovide-lang
	dev-racket/gregor-lib
	dev-racket/fancy-app
	dev-racket/compose-app
"
RDEPEND="${DEPEND}"
