# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mbutterick/beautiful-racket"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.19
	GH_COMMIT="b0d133f4ba4149ea506d8b0dbd3845c915efdd06"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Subpackage with just the br/macro and br/syntax modules"
HOMEPAGE="https://github.com/mbutterick/beautiful-racket"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

S="${S}/beautiful-racket-macro"
