# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="RayRacine/string-util"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.08
	GH_COMMIT="4af2c3e5f21accaa4bc8f02db2bfe8f1b9a62223"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Additional string utilities in Typed Racket."
HOMEPAGE="https://gitlab.com/RayRacine/string-util"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/list-util
	dev-racket/opt
"
RDEPEND="${DEPEND}"
