# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dedbox/racket-algebraic"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.08.10
	GH_COMMIT="706b2d01ab735a01e372c33da49995339194e024"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Algebraic Racket"
HOMEPAGE="https://github.com/dedbox/racket-algebraic"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/texmath
"
RDEPEND="${DEPEND}"
