# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="stchang/parsack"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.02.28
	GH_COMMIT="3a02d3788b7bb5d6b4a05b3b2651d9309005c0fd"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A basic Parsec (Haskell's monadic parser combinator library) implementation."
HOMEPAGE="https://github.com/stchang/parsack"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
