# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="zyrolasting/stripe-integration"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.09.26
	GH_COMMIT="8675b005992576a1df07f6687b271be026049eaa"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Unofficial Stripe API integration with Racket"
HOMEPAGE="https://github.com/zyrolasting/stripe-integration"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
