# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="EFanZh/cover-cobertura"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.11.17
	GH_COMMIT="2a63c5ef4544b3c6ca928c596ae81e4490f14c14"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the cover-cobertura Racket package"
HOMEPAGE="https://github.com/EFanZh/cover-cobertura"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/cover
"
RDEPEND="${DEPEND}"
