# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="GPRicci/secd"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.07.31
	GH_COMMIT="cebf4c32d4c48c6d964449788c0e708524872120"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An SECD to ARM Assembler compiler, supporting a small subset of instructions."
HOMEPAGE="https://github.com/GPRicci/secd"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/brag
	dev-racket/beautiful-racket-lib
"
RDEPEND="${DEPEND}"
