# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jsmaniac/scribble-enhanced"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.04
	GH_COMMIT="d4fe76d1899b540e2806520a3acbf4afdf5abb88"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the scribble-enhanced Racket package"
HOMEPAGE="https://github.com/jsmaniac/scribble-enhanced"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/mutable-match-lambda
	dev-racket/reprovide-lang
"
RDEPEND="${DEPEND}"
