# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/my-cond"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.12.15
	GH_COMMIT="1bb7066f69ba4619ac7d2ea0c292f80b78c5503b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the my-cond Racket package"
HOMEPAGE="https://github.com/AlexKnauth/my-cond"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/sweet-exp
	dev-racket/sweet-exp-lib
"
RDEPEND="${DEPEND}"
