# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="wilbowma/cur"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.17
	GH_COMMIT="7ce536c14e4e18cc84a7011a70f37cb98e21cf97"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Dependent types and meta-programming"
HOMEPAGE="https://github.com/wilbowma/cur"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/cur-test
	dev-racket/cur-doc
	dev-racket/cur-lib
"
RDEPEND="${DEPEND}"

S="${S}/cur"
