# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="petterpripp/gsl-rng"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.06.20
	GH_COMMIT="c7d98142b55ab990af8d1d27d59be17058755dcd"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Interface to GNU GSL Random Number Generation"
HOMEPAGE="https://github.com/petterpripp/gsl-rng"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
