# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dstorrs/struct-plus-plus"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.07.23
	GH_COMMIT="a7b62bf51214031a969e0503143f4ee64c9f6fe2"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the struct-plus-plus Racket package"
HOMEPAGE="https://github.com/dstorrs/struct-plus-plus"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/syntax-classes-lib
	dev-racket/handy
"
RDEPEND="${DEPEND}"
