# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="thoughtstem/racket-chipmunk"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.12.13
	GH_COMMIT="152c9c4758f59ade9db01614e89e946eb39de168"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Chipmunk bindings for Racket."
HOMEPAGE="https://github.com/thoughtstem/racket-chipmunk"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
