# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="samdphillips/raco-pkg-env"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.21
	GH_COMMIT="16e6ea731c360efeadd3c8ff5683e72cf5c3c2ea"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="virtualenv like tool for Racket"
HOMEPAGE="https://github.com/samdphillips/raco-pkg-env"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/raco-pkg-env-lib
"
RDEPEND="${DEPEND}"

S="${S}/raco-pkg-env"
