# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="97jaz/cldr-numbers-modern"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="625428099b3f8cd264955a283dddc176a6080ba1"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="API for cldr-numbers-modern data set"
HOMEPAGE="https://github.com/97jaz/cldr-numbers-modern"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/cldr-core
"
RDEPEND="${DEPEND}"
