# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/scribble-code-examples"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.02.09
	GH_COMMIT="18166292d8d491881cf5ac98352c23bd5ebec312"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A scribble examples form that works with non-s-exp languages"
HOMEPAGE="https://github.com/AlexKnauth/scribble-code-examples"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/scribble-code-examples-lib
"
RDEPEND="${DEPEND}"

S="${S}/scribble-code-examples"
