# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Metaxal/search-list-box"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.08.03
	GH_COMMIT="b54b28d4bd8d2d2426d3e211570a811ea3421f5b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A list-box% with a search field"
HOMEPAGE="https://github.com/Metaxal/search-list-box"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
