# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mordae/racket-pex"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="57997dcdcf5533249d65a9040d55763b22dda57a"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Apollo Art PEx System Control"
HOMEPAGE="https://github.com/mordae/racket-pex"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/libserialport
	dev-racket/mordae
"
RDEPEND="${DEPEND}"
