# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dedbox/racket-values"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.09.04
	GH_COMMIT="beec5757368e9bf64a42c7b0f5e5a0fa49f622c5"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="functional multi-valued computation"
HOMEPAGE="https://github.com/dedbox/racket-values"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
