# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="amkhlv/amkhlv"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.16
	GH_COMMIT="8322e6d1a779df5d696b62b68d64ca1d59f5b773"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A tool for preparing HTML slides with LaTeX formulas, based on Scribble"
HOMEPAGE="https://github.com/amkhlv/amkhlv"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

S="${S}/bystroTeX"
