# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="tail-reversion/elle"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.01.19
	GH_COMMIT="87053a6ba8e12c15823395149fe74a62ebb77fee"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the elle Racket package"
HOMEPAGE="https://github.com/tail-reversion/elle"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/elle-doc
	dev-racket/elle-lib
"
RDEPEND="${DEPEND}"

S="${S}/elle"
