# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="pmatos/racket-bv"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.05.30
	GH_COMMIT="3d1fdc02432dc7bb839802f499834bd3345e54bf"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Bitvectors for Racket a-la Rosette"
HOMEPAGE="https://github.com/pmatos/racket-bv"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rosette
	dev-racket/quickcheck
	dev-racket/mischief
"
RDEPEND="${DEPEND}"
