# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="nuty/vela"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.05.18
	GH_COMMIT="5998a2cf7101a9b98d91fce11c4c1d86f0f5a274"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Simple web framework to build RESTful app in Racket."
HOMEPAGE="https://github.com/nuty/vela"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/vela-docs
	dev-racket/vela-lib
"
RDEPEND="${DEPEND}"

S="${S}/vela"
