# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="RayRacine/list-util"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.08
	GH_COMMIT="e538fd85b38e7bfcaf2aace75ced7d0183e91073"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Additional List utilities in Typed Racket."
HOMEPAGE="https://gitlab.com/RayRacine/list-util"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
