# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="LeifAndersen/racket-calendar"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.12.06
	GH_COMMIT="1c38c3804b8f4d87d5036d67018839276bdf6875"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the calendar Racket package"
HOMEPAGE="https://github.com/LeifAndersen/racket-calendar"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/gregor-lib
"
RDEPEND="${DEPEND}"
