# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mbutterick/css-tools"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.18
	GH_COMMIT="a33fc646904b99cece497b5b221a8d83bdc4d96f"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Tools for generating & manipulating CSS (unstable)"
HOMEPAGE="https://github.com/mbutterick/css-tools"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/sugar
"
RDEPEND="${DEPEND}"
