# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="philnguyen/json-type-provider"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.02.26
	GH_COMMIT="f96d3f212519f4ff2aef828e7b891971b82babb8"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A well-typed JSON parser for Typed Racket inspired by Type Provider"
HOMEPAGE="https://github.com/philnguyen/json-type-provider"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/json-type-provider
"
RDEPEND="${DEPEND}"

S="${S}/json-type-provider"
