# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dalev/minikanren-typed-racket"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.03
	GH_COMMIT="83262e26f03581c99a072db03dfbafb1ab9401f2"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An implementation of miniKanren in typed racket."
HOMEPAGE="https://github.com/dalev/minikanren-typed-racket"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
