# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="pnwamk/typeset-rewriter"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="9737f385b57a74564221ebd719c01f4180fbf6f8"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Simple, low-level rewriter tools for typesetting PLT Redex models"
HOMEPAGE="https://github.com/pnwamk/typeset-rewriter"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
