# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="zyrolasting/tweedledum"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.05.06
	GH_COMMIT="64417ba609ea7a5db1ca7c25baa63dfb59a3955e"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Conflicts with tweedledee, or any other package with a hill/king module."
HOMEPAGE="https://github.com/zyrolasting/tweedledum"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
