# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="calvis/cKanren/"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="8714bdd442ca03dbf5b1d6250904cbc5fd275e68"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Constraint programming language"
HOMEPAGE="https://github.com/calvis/cKanren/"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
