# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="sorawee/mixfix"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.03.18
	GH_COMMIT="db91d60448adbce889d3c85dd7553274f8db971a"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Mixfix for Racket"
HOMEPAGE="https://github.com/sorawee/mixfix"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
