# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="nixpulvis/parser-combinator"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.05.05
	GH_COMMIT="9635c0479c1841e122a75faa35d1d76333ef3cb6"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Parser / Lexer Library, and JSON Implementation."
HOMEPAGE="https://github.com/nixpulvis/parser-combinator"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
