# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/glass"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.08.21
	GH_COMMIT="a5b25ed7716598b49ccdb5b6917d0eacd95764cf"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An optics (lenses, prisms, traversals, etc.) library."
HOMEPAGE="https://github.com/jackfirth/glass"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rebellion
	dev-racket/fancy-app
"
RDEPEND="${DEPEND}"
