# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jeapostrophe/pict3d"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.08.28
	GH_COMMIT="b73e77c66461081934eaeeb17f079841a0118387"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Modern 3D engine with a purely functional interface"
HOMEPAGE="https://github.com/jeapostrophe/pict3d"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/pfds
"
RDEPEND="${DEPEND}"
