# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="bbusching/libgit2"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.05.07
	GH_COMMIT="6d6a007543900eb7a6fbbeba55850288665bdde5"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Racket bindings for the Libgit2 library."
HOMEPAGE="https://github.com/bbusching/libgit2"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
