# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="apg/netrc"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="af814d20a77910ab6de2161ac37d02586604a192"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Find entries in ~/.netrc files"
HOMEPAGE="https://github.com/apg/netrc"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
