# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="LiberalArtist/icns"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.28
	GH_COMMIT="979cbc32e1d1e245f970e53c2098fbad0f538629"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A Racket library for working with Apple's .icns icon file format."
HOMEPAGE="https://github.com/LiberalArtist/icns"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
