# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="apg/statsd-rkt"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="39a640686053be83442bfb129a279b8d00d6a177"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="statsd client for racket"
HOMEPAGE="https://github.com/apg/statsd-rkt"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
