# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dstorrs/thread-with-id"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.06.15
	GH_COMMIT="0b5908a810b710bae7a8e0bc89f6468c81d12f92"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the thread-with-id Racket package"
HOMEPAGE="https://github.com/dstorrs/thread-with-id"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
