# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/package-analysis"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.08.30
	GH_COMMIT="785bc9b1eac503c9359d9d08936422f6f47ce82b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A package for analyzing the Racket package ecosystem"
HOMEPAGE="https://github.com/jackfirth/package-analysis"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rebellion
"
RDEPEND="${DEPEND}"
