# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="michaelballantyne/multiscope"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.09.29
	GH_COMMIT="bc59bd53462a72ed3e67ec2555e94e871bc7e314"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the multiscope Racket package"
HOMEPAGE="https://github.com/michaelballantyne/multiscope"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
