# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="greghendershott/wffi"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="03bd59bea2aa6e0a855de28fb5bb18769ed04b3b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the wffi Racket package"
HOMEPAGE="https://github.com/greghendershott/wffi"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/http
"
RDEPEND="${DEPEND}"
