# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="rmculpepper/crypto"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.01.25
	GH_COMMIT="fec745e8af7e3f4d5eaf83407dde2817de4c2eb0"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Cryptography library"
HOMEPAGE="https://github.com/rmculpepper/crypto"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/gmp-lib
	dev-racket/binaryio-lib
	dev-racket/base64-lib
	dev-racket/asn1-lib
"
RDEPEND="${DEPEND}"

S="${S}/crypto-lib"
