# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="vishesh/elasticsearch.rkt"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.09.24
	GH_COMMIT="160e2be024a21e7b043b93a5d45eaaca8e3713a1"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the elasticsearch Racket package"
HOMEPAGE="https://github.com/vishesh/elasticsearch.rkt"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
