# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="JoaoBrlt/drracket-one-dark"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.03.05
	GH_COMMIT="7b9dbd998e8976f37f98cf1f8fa25c4f4631dcef"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Atom's iconic One Dark color scheme for DrRacket!"
HOMEPAGE="https://github.com/JoaoBrlt/drracket-one-dark"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
