# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="eeide/racr"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="bee5a520ec663aa58673367a453c5d2a97e8d79c"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the racr Racket package"
HOMEPAGE="https://github.com/eeide/racr"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
