# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Metaxal/bazaar/"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.31
	GH_COMMIT="8432d3c5398225a4bfb5ed5c25a1beffa06409ec"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A personal collection of useful definitions. Quite unstable."
HOMEPAGE="https://github.com/Metaxal/bazaar/"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
