# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="thinkmoore/racket-fuse"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="5c24b1e135e97ff6c8e49b363f01ff21c28ecf8b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Library for creating user-space filesystems with FUSE"
HOMEPAGE="https://github.com/thinkmoore/racket-fuse"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
