# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/afl"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.10.13
	GH_COMMIT="13b5f8c6c71f0eb66a4f1e71f295bfda88f526bb"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="a lang-extension that provides rackjure-like anonymous function literals"
HOMEPAGE="https://github.com/AlexKnauth/afl"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/scribble-code-examples
	dev-racket/rackjure
	dev-racket/hygienic-reader-extension
"
RDEPEND="${DEPEND}"
