# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="default-kramer/morsel"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.06.22
	GH_COMMIT="10cf376f07755f066cbbfc2d242c104f103b33da"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="documentation for morsel-lib"
HOMEPAGE="https://github.com/default-kramer/morsel"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/doc-coverage
	dev-racket/morsel-lib
"
RDEPEND="${DEPEND}"

S="${S}/morsel-doc"
