# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="schuster/racket-irc"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.05.21
	GH_COMMIT="50637fdc83da6c415b7ae26683a56d394c9ffe61"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An IRC client library."
HOMEPAGE="https://github.com/schuster/racket-irc"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
