# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="plt/handin"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.10.07
	GH_COMMIT="3c31daccf0f61bb06aa65e36d72acc0ef2f453da"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Handin server and client template"
HOMEPAGE="https://github.com/plt/handin"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
