# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Bogdanp/koyo-postmark"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.03.15
	GH_COMMIT="ceeb619d555ef49c2cec42c0b890a97fd1377f89"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A Postmark mail adapter for koyo. (docs and implementation)"
HOMEPAGE="https://github.com/Bogdanp/koyo-postmark"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/koyo-doc
	dev-racket/postmark-client
	dev-racket/koyo-lib
"
RDEPEND="${DEPEND}"
