# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="maueroats/wy-posn-util"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.02.19
	GH_COMMIT="2665d883bba8f1f720e469b8f971e385be05eb05"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Functions to work with 2d vectors (posn) in 2htdp."
HOMEPAGE="https://github.com/maueroats/wy-posn-util"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
