# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mosceo/tetris"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.12.06
	GH_COMMIT="bbf9dc58b8b1606f574ebf1a466eeef278689a68"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A colorful version of tetris."
HOMEPAGE="https://github.com/mosceo/tetris"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
