# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="herbie-fp/egg-herbie"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.08.19
	GH_COMMIT="c54bde206b82671cbb2ef262504b63cf2fa131e5"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the egg-herbie-windows Racket package"
HOMEPAGE="https://github.com/herbie-fp/egg-herbie"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
