# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dstorrs/racket-test-more"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.05.02
	GH_COMMIT="659c90a27ffd575bf95b0eb60ec594a3e7420f16"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the test-more Racket package"
HOMEPAGE="https://github.com/dstorrs/racket-test-more"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
