# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="alex-hhh/map-widget"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.06
	GH_COMMIT="49626f13fd8af53eee732400f60a8ffdcb5f56e9"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A Racket GUI Widget to display maps based on OpenStreetMap tiles"
HOMEPAGE="https://github.com/alex-hhh/map-widget"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/al2-test-runner
	dev-racket/geoid
	dev-racket/http-easy
"
RDEPEND="${DEPEND}"
