# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="xgqt/rbulkresizer"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.25
	GH_COMMIT="77400cd87fc3d81a935606b71ece940c3ec53c0f"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Graphical bulk picture resize tool"
HOMEPAGE="https://gitlab.com/xgqt/rbulkresizer"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
