# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="xgqt/rbulkresizer"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.13
	GH_COMMIT="58d32a47bbd8a7447769212765b42ea80a4f051a"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Graphical bulk picture resize tool"
HOMEPAGE="https://gitlab.com/xgqt/rbulkresizer"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
