# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="massung/r-cade"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.20
	GH_COMMIT="aede5ea5b019775d5beba219baf6a19ef4d4bfca"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Retro game engine."
HOMEPAGE="https://github.com/massung/r-cade"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/csfml
"
RDEPEND="${DEPEND}"
