# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="malcolmstill/pollen-count"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="c4da923debcf40d0558ea4cb97c8a7bd4f35f34b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the pollen-count Racket package"
HOMEPAGE="https://github.com/malcolmstill/pollen-count"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/txexpr
"
RDEPEND="${DEPEND}"
