# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="johnnyodonnell/racket-lambda-runtime"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.04.14
	GH_COMMIT="2a8410a11e93bf9371eac6f90a37c582ef5e1897"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the racket-lambda-runtime Racket package"
HOMEPAGE="https://github.com/johnnyodonnell/racket-lambda-runtime"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
