# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/euclid"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.21
	GH_COMMIT="bd64f8f2c7e60ce6d435c7f0241cf3dfffe6d297"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Data structures and algorithms related to Euclidean geometry"
HOMEPAGE="https://github.com/jackfirth/euclid"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rebellion
"
RDEPEND="${DEPEND}"
