# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Bogdanp/racket-net-ip"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.10.07
	GH_COMMIT="fec61684f123f042ae0236e9ee702fb0591bc502"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="IP address utilities (docs only)."
HOMEPAGE="https://github.com/Bogdanp/racket-net-ip"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/net-ip-lib
"
RDEPEND="${DEPEND}"

S="${S}/net-ip-doc"
