# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mordae/racket-rtnl/"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="53cf9eb3d1927cd4357ebdf785ffb58cacff6c3e"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Racket FFI Bindings for the Route-Netlink Library"
HOMEPAGE="https://github.com/mordae/racket-rtnl/"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/misc1
"
RDEPEND="${DEPEND}"
