# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="eu90h/rackdis"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="975aeb46b6432d2359fb1c625f69ae5b97f450d1"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Redis bindings"
HOMEPAGE="https://github.com/eu90h/rackdis"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
