# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="racket/srfi"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.11.05
	GH_COMMIT="bc905ddcbeaa84502a015f140ddecd0d2772d576"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="parts of srfi implementation that are licensed restrictively"
HOMEPAGE="https://github.com/racket/srfi"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

S="${S}/srfi-lib-nonfree"
