# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dannypsnl/mini-theme"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.09
	GH_COMMIT="3410442a1eb9b7ad51d74179df1f92c64637b9c8"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A minimal DrRacket theme"
HOMEPAGE="https://github.com/dannypsnl/mini-theme"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
