# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="bennn/scribble-abbrevs"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.02.26
	GH_COMMIT="ecd6328cf21cd869c867587212fc0d8fdbf38f85"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Scribble-to-LaTeX helper functions"
HOMEPAGE="https://github.com/bennn/scribble-abbrevs"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rackunit-abbrevs
	dev-racket/reprovide-lang
"
RDEPEND="${DEPEND}"
