# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="samth/persistent-union-find"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="f95278e362550a59dae327bd15f9f609009de6d0"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A persistent implementation of the union-find data structure"
HOMEPAGE="https://github.com/samth/persistent-union-find"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/persistent-array
"
RDEPEND="${DEPEND}"
