# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dented42/latex-utils"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="631ad9b13b837f4109932252c85bc1bf6f0ae752"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Some utilities for generating LaTeX markup of various descriptions."
HOMEPAGE="https://github.com/dented42/latex-utils"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/seq-no-order
"
RDEPEND="${DEPEND}"
