# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="car.margiotta/google-spreadsheet-api"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.08
	GH_COMMIT="081c8a9543b5d1f0a5329de62c87eec5f12e8b9c"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Racket interface for Google Spreadsheet APIs"
HOMEPAGE="https://gitlab.com/car.margiotta/google-spreadsheet-api"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/scribble-code-examples
	dev-racket/net-jwt
	dev-racket/crypto
"
RDEPEND="${DEPEND}"
