# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="takikawa/ppict-slide-grid"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="1e992183dbfc695882bb612bb5b8b32515adeee2"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the ppict-slide-grid Racket package"
HOMEPAGE="https://github.com/takikawa/ppict-slide-grid"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
