# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="macrotypefunctors/serialize-syntax-introducer"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.06.17
	GH_COMMIT="5944d9f32df50b608c3493a7fd6a510afabf8fd3"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the serialize-syntax-introducer Racket package"
HOMEPAGE="https://github.com/macrotypefunctors/serialize-syntax-introducer"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
