# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="spritely/goblins"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.08
	GH_COMMIT="aa17ae4d08582eaa7b2d999edc940b9076d9fac5"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Goblins is a lightweight actor model library."
HOMEPAGE="https://gitlab.com/spritely/goblins"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/pk
	dev-racket/syrup
	dev-racket/crypto
"
RDEPEND="${DEPEND}"

S="${S}/goblins"
