# Copyright 1999-2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

GH_DOM="github.com"
GH_REPO="yanyingwang/scribble-rainbow-delimiters"
GH_COMMIT="5ddb7a7563686a8b2c84e526aace9c0ca23c76ef"

inherit gh racket

DESCRIPTION="Colorizing matched brackets of codes on HTML pages generated by Racket Scribble"
HOMEPAGE="https://github.com/yanyingwang/scribble-rainbow-delimiters"

LICENSE="all-rights-reserved"
SLOT="0"
KEYWORDS="~amd64 ~arm ~ppc ~ppc64 ~x86"
RESTRICT="mirror"
