# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

GH_DOM="github.com"
GH_REPO="yanyingwang/scribble-rainbow-delimiters"
GH_COMMIT="4224d9ae0029bd80b60f477199f8fad2427da8f0"

inherit racket gh

DESCRIPTION="Colorizing matched brackets of codes on HTML pages generated by Racket Scribble"
HOMEPAGE="https://github.com/yanyingwang/scribble-rainbow-delimiters"

LICENSE="all-rights-reserved"
SLOT="0"
KEYWORDS="~amd64"
RESTRICT="mirror"
