# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/icfp2017-artifact-auas7pp"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.08.04
	GH_COMMIT="ff9eca58487ec393fc2d8580e5d1aafedcd20808"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the icfp2017-minikanren Racket package"
HOMEPAGE="https://github.com/AlexKnauth/icfp2017-artifact-auas7pp"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

S="${S}/src"
