# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Kalimehtar/thread-utils"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.06.21
	GH_COMMIT="f81ebfaf8453acb3a938917c1a505c94af92ef87"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Error-safe infinite loop and until-timeout"
HOMEPAGE="https://github.com/Kalimehtar/thread-utils"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
