# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="takikawa/minikanren/"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="659404d009e9cec9695805f4d4465447796a663a"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A Planet 2 package for minikanren"
HOMEPAGE="https://github.com/takikawa/minikanren/"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
