# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="zaoqil/apply"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.01.21
	GH_COMMIT="1d7d138179cd02e2b10eab29748d08b76d91c69d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the apply Racket package"
HOMEPAGE="https://github.com/zaoqil/apply"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

S="${S}/apply"
