# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="lwhjp/binary-class-riff"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.09.06
	GH_COMMIT="ddad0c7fa1e1f7a3b990809bcccbd521204e2fd0"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Classes for reading and writing RIFF files"
HOMEPAGE="https://github.com/lwhjp/binary-class-riff"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/binary-class
"
RDEPEND="${DEPEND}"
