# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="greghendershott/echonest/"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="fd7d6511231bb4304cfd10260825e86ac33c3ddc"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Wrapper for The Echo Nest web API."
HOMEPAGE="https://github.com/greghendershott/echonest/"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rackjure
	dev-racket/wffi
"
RDEPEND="${DEPEND}"
