# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="soegaard/cairo"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.07.04
	GH_COMMIT="537ba989c6dd0ed71e5da38995306955fcae84d5"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the cairo-lib Racket package"
HOMEPAGE="https://github.com/soegaard/cairo"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

S="${S}/cairo-lib"
