# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="cbiffle/ruckus"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="62cd4a00837783a88a007c2d5979909a4e86ca0f"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Procedural CAD system for solid modeling"
HOMEPAGE="https://github.com/cbiffle/ruckus"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/opengl
"
RDEPEND="${DEPEND}"
