# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="stamourv/feature-profile"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.09.02
	GH_COMMIT="cc96e3aa8efe71c013f662c60e2b0d9231b27f97"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Profile that measures time spent in language/library features"
HOMEPAGE="https://github.com/stamourv/feature-profile"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
