# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mbutterick/xenomorph"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.18
	GH_COMMIT="0ea62de7d688effc1179589215529537e3eeb858"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="binary encoder [in development]"
HOMEPAGE="https://github.com/mbutterick/xenomorph"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/debug
	dev-racket/sugar
	dev-racket/beautiful-racket-lib
"
RDEPEND="${DEPEND}"
