# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dedbox/racket-glsl"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.10.25
	GH_COMMIT="6853bcb4324a10deb2cec70e59fb8b401a45e9f3"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="The OpenGL Shader Language 4.5 (GLSL)"
HOMEPAGE="https://github.com/dedbox/racket-glsl"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
