# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="zyrolasting/unlike-assets"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.24
	GH_COMMIT="7fb08d6902d34399c96a325d68fd27f1ff84813b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="(OLD EDITION) Implementation of unlike-assets"
HOMEPAGE="https://github.com/zyrolasting/unlike-assets"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/kinda-ferpy
	dev-racket/graph-lib
	dev-racket/ansi-color
	dev-racket/file-watchers
"
RDEPEND="${DEPEND}"

S="${S}/unlike-assets-lib"
