# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Kalimehtar/russian-lang"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.09
	GH_COMMIT="3966db07cf44d5c410d835670eb36796d11c7fba"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Programming language based on russian language"
HOMEPAGE="https://github.com/Kalimehtar/russian-lang"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
