# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Raymo111/cs135-drtools"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.12.17
	GH_COMMIT="75c7041944ac489cacfe9327a7a936aafb576983"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="DrRacket Tools for CS 135 course at UWaterloo."
HOMEPAGE="https://github.com/Raymo111/cs135-drtools"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
