# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jbclements/ebml/"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.12.18
	GH_COMMIT="2ec0b537cf88dfbcf791f28a3ecd45583ff6295a"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A library for reading and writing EBML files."
HOMEPAGE="https://github.com/jbclements/ebml/"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
