# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/predicates"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="ba6b82864a6bdb2b0aa42d3a493effe54d44e4e1"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the predicates Racket package"
HOMEPAGE="https://github.com/jackfirth/predicates"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
