# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dyoo/stardate/"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="580558886983d73916c355e21400310a59729be5"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Compute the current TNG stardate."
HOMEPAGE="https://github.com/dyoo/stardate/"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
