# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="willghatch/racket-rash"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.03.16
	GH_COMMIT="c40c5adfedf632bc1fdbad3e0e2763b134ee3ff5"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="The Reckless Racket Shell.  For interactions and scripting."
HOMEPAGE="https://github.com/willghatch/racket-rash"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/udelim
	dev-racket/linea
	dev-racket/shell-pipeline
	dev-racket/basedir
"
RDEPEND="${DEPEND}"

S="${S}/rash"
