# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Kalimehtar/binary-class-exif"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="8d475c4dd72de90decedeb3fc0acd53d9cf6f60d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Class for reading and writing Exif in JPEG or TIFF"
HOMEPAGE="https://github.com/Kalimehtar/binary-class-exif"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/binary-class
"
RDEPEND="${DEPEND}"
