# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jpathy/hidapi"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.10.25
	GH_COMMIT="91c5e5b8eb7380d3b6031d736e6d8fc9121a7cb0"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Racket bindings to hidapi library."
HOMEPAGE="https://github.com/jpathy/hidapi"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
