# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="takikawa/pprint.plt"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.12.21
	GH_COMMIT="c85b4adcf26d3afc5b812d21b3a8f31d1fc6f853"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A universal pretty printing library"
HOMEPAGE="https://github.com/takikawa/pprint.plt"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/dherman-struct
"
RDEPEND="${DEPEND}"
