# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="takikawa/pprint.plt"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.25
	GH_COMMIT="f078284e092f98c5c15278b334f9b5b32828e9b6"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A universal pretty printing library"
HOMEPAGE="https://github.com/takikawa/pprint.plt"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/dherman-struct
"
RDEPEND="${DEPEND}"
