# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="bennn/redex-abbrevs"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.02.27
	GH_COMMIT="3205f90c07e5614ad90cea59eb59b7bc883167df"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Tools for PLT Redex"
HOMEPAGE="https://github.com/bennn/redex-abbrevs"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/redex-abbrevs-doc
	dev-racket/redex-abbrevs-lib
"
RDEPEND="${DEPEND}"

S="${S}/redex-abbrevs"
