# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="pyohannes/racket-symalg"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.04.01
	GH_COMMIT="5c551e9fcead240dcc70261563c5b981428ca67a"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Expressing and manipulating symbolic algebraic expressions in Racket."
HOMEPAGE="https://github.com/pyohannes/racket-symalg"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/multimethod
"
RDEPEND="${DEPEND}"
