# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="the-language/zKanren2"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.03.23
	GH_COMMIT="82c936ed11fa703b3b26895b3a2d7b7f379a8c35"
	KEYWORDS="~amd64"
fi

RACKET_PN="zKanren"

inherit gh racket

DESCRIPTION="-"
HOMEPAGE="https://github.com/the-language/zKanren2"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
