# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="stchang/macrotypes"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.16
	GH_COMMIT="220552416edf5646d796668176a473e4271205b2"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the macrotypes-test Racket package"
HOMEPAGE="https://github.com/stchang/macrotypes"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rackunit-macrotypes-lib
	dev-racket/macrotypes-example
"
RDEPEND="${DEPEND}"

S="${S}/macrotypes-test"
