# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jeapostrophe/automata"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.01.26
	GH_COMMIT="6abe851b83b18fcdcb8f2b19ab87cdabc90c71ce"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="a library for defining efficient automata using match patterns"
HOMEPAGE="https://github.com/jeapostrophe/automata"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/automata-lib
"
RDEPEND="${DEPEND}"

S="${S}/automata-test"
