# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="RayRacine/word"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.08
	GH_COMMIT="280659a27d2e3581fe64e8d406435cbcbadf3182"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Signed and Unsigned Word datatype for Racket using refinement types."
HOMEPAGE="https://gitlab.com/RayRacine/word"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
