# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="pezipink/asi64"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.01.02
	GH_COMMIT="81e61a25a6f35e137df6326353b9c54f50f2d829"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="The Racket based 6502 assembler"
HOMEPAGE="https://github.com/pezipink/asi64"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
