# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="robertkleffner/glossolalia"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.08.04
	GH_COMMIT="2f7d6c2865267aaee4709ca6640243b89ecf6c6d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the glossolalia Racket package"
HOMEPAGE="https://github.com/robertkleffner/glossolalia"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/br-parser-tools-lib
	dev-racket/beautiful-racket-lib
	dev-racket/beautiful-racket
	dev-racket/brag
"
RDEPEND="${DEPEND}"
