# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jeapostrophe/iswim"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.08.04
	GH_COMMIT="7d6fe87391475b22828a39b344fd7b983f7018f7"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="iswim implementation"
HOMEPAGE="https://github.com/jeapostrophe/iswim"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
