# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mflatt/plai-typed-s-exp-match"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="e010d9718916394b1b3545cb2f7a49c27904e873"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Simple S-expression matcher for use with plai-typed"
HOMEPAGE="https://github.com/mflatt/plai-typed-s-exp-match"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/plai-typed
"
RDEPEND="${DEPEND}"
