# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/no-vert-bar-lang"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.02.11
	GH_COMMIT="3e31489f2b3aff73f50cade704b724b5578af7fb"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="a lang-extension that reads | as a normal character"
HOMEPAGE="https://github.com/AlexKnauth/no-vert-bar-lang"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
