# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jsmaniac/backport-template-pr1514"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.03.05
	GH_COMMIT="a6c3611fcddb8d8a67531694c9b8c2c4f89bbb0f"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the backport-template-pr1514 Racket package"
HOMEPAGE="https://github.com/jsmaniac/backport-template-pr1514"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/version-case
"
RDEPEND="${DEPEND}"
