# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="zyrolasting/kinda-ferpy"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.02.11
	GH_COMMIT="d70b3fd0dc7c8793a954599ed708414a481afab1"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An implicit functional reactive model based on MaiaVictor's PureState library"
HOMEPAGE="https://github.com/zyrolasting/kinda-ferpy"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
