# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jsmaniac/typed-map"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.04
	GH_COMMIT="7a70650b6f8e1222fe1e4ebd2fb6b9b2489301e2"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Documentation for typed-map"
HOMEPAGE="https://github.com/jsmaniac/typed-map"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/typed-map-lib
	dev-racket/aful
"
RDEPEND="${DEPEND}"

S="${S}/typed-map-doc"
