# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mordae/racket-tandem"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="fa6bae480f6f4a3ae411ca5c3bad7ae5f8d106ac"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Cooperative Communication Framework for Racket"
HOMEPAGE="https://github.com/mordae/racket-tandem"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/misc1
"
RDEPEND="${DEPEND}"
