# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mbutterick/txexpr"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.18
	GH_COMMIT="41d217580363c9cb11e2321c79f89c3cd7a604c1"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Handy tools for working with HTML-style tagged X-expressions"
HOMEPAGE="https://github.com/mbutterick/txexpr"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/sugar
"
RDEPEND="${DEPEND}"
