# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="theia-ide/racket-language-server"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.04.10
	GH_COMMIT="e397a130676504fc8b053e6b1f48d49b77b9ad98"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Implementation of the Language Server Protocol for Racket."
HOMEPAGE="https://github.com/theia-ide/racket-language-server"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
