# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="florence/cover"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.02.27
	GH_COMMIT="ad50ffa8f6246053bec24b39b9cae7fad1534373"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A code coverage tool"
HOMEPAGE="https://github.com/florence/cover"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/cover-doc
	dev-racket/cover-lib
"
RDEPEND="${DEPEND}"

S="${S}/cover"
