# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="LiberalArtist/2048"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.28
	GH_COMMIT="ef07f6f91d58f00c50aafb239926596477e56e50"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="The game of 2048 in Racket"
HOMEPAGE="https://github.com/LiberalArtist/2048"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/icns
"
RDEPEND="${DEPEND}"
