# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="wilbowma/scribble-minted"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.04
	GH_COMMIT="0639c54c84c3294e575c1e70b2d17f5537c1750a"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A scribble library for using pygmentize (library only)."
HOMEPAGE="https://github.com/wilbowma/scribble-minted"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

S="${S}/scribble-minted-lib"
