# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="philnguyen/termination"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.05.30
	GH_COMMIT="1d05c1bf8e9bd59d2fbaaa213b490fd8e59644bd"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Dynamic enforcement of size-change termination"
HOMEPAGE="https://github.com/philnguyen/termination"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/traces
	dev-racket/unreachable
	dev-racket/set-extras
	dev-racket/bnf
"
RDEPEND="${DEPEND}"

S="${S}/termination"
