# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jsmaniac/delay-pure"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.04
	GH_COMMIT="19541b8094b1aac23268f13d308202627275a360"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the delay-pure Racket package"
HOMEPAGE="https://github.com/jsmaniac/delay-pure"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/version-case
	dev-racket/phc-toolkit
	dev-racket/type-expander
"
RDEPEND="${DEPEND}"
