# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="g-gundam/yotsubAPI"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="cbf312862fc4e94deb74790a2756d5745e5463fc"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A Racket Client for the 4chan API"
HOMEPAGE="https://github.com/g-gundam/yotsubAPI"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
