# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="yanyingwang/timable"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.25
	GH_COMMIT="05eab1f2a33c8c7d217d203ed6615cb66a24ea61"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the timable Racket package"
HOMEPAGE="https://github.com/yanyingwang/timable"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/scribble-rainbow-delimiters
	dev-racket/gregor
"
RDEPEND="${DEPEND}"
