# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="pythondude325/basm"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.08
	GH_COMMIT="02b7d75eaddda765729820f79a13b54da6e1db14"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the basm Racket package"
HOMEPAGE="https://gitlab.com/pythondude325/basm"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
