# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="thoughtstem/english"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.02.20
	GH_COMMIT="b03f3b203fdbc11780291e09a528ff0590b5802b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Utilities for generating English text strings -- e.g. plurals"
HOMEPAGE="https://github.com/thoughtstem/english"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
