# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="zyrolasting/tweedledee"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.05.06
	GH_COMMIT="f0919e3816b448cea75db7d9121f355a9fe4edec"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Conflicts with tweedledum, or any other package with a hill/king module."
HOMEPAGE="https://github.com/zyrolasting/tweedledee"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
