# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="zyrolasting/dynamic-xml"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.05.06
	GH_COMMIT="0e41c5b26fd0780604d0ecdc27d1e2c40faceb97"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Apply keyword procedures in a given Racket namespace using X-expressions."
HOMEPAGE="https://github.com/zyrolasting/dynamic-xml"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
