# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="cemcutting/forged-ocelot"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.08.04
	GH_COMMIT="f28a7012348b9096ede5cb1da64ef6544686b205"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the forged-ocelot Racket package"
HOMEPAGE="https://github.com/cemcutting/forged-ocelot"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rosette
"
RDEPEND="${DEPEND}"
