# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="philnguyen/traces"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.03.22
	GH_COMMIT="de08fadc1b1d73362c7b6d83f0dd9a4c9dc36743"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the traces Racket package"
HOMEPAGE="https://github.com/philnguyen/traces"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

S="${S}/traces"
