# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="bennn/rackunit-abbrevs"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.02.23
	GH_COMMIT="507e8b64307d8e14fd66adc1ef89833a102f75b9"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Iterated RackUnit tests"
HOMEPAGE="https://github.com/bennn/rackunit-abbrevs"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
