# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jeapostrophe/rmc"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="e11425287cfecb3940f75a25a29f9b74826c2605"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Racket-made C"
HOMEPAGE="https://github.com/jeapostrophe/rmc"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/chk
	dev-racket/pprint
"
RDEPEND="${DEPEND}"
