# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jbclements/t-test"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.03.16
	GH_COMMIT="eb5cc28868689324f6c27722d2516715570cab97"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Simple implementations of Welch's and Student's t-tests"
HOMEPAGE="https://github.com/jbclements/t-test"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
