# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mflatt/plai-typed"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.08.16
	GH_COMMIT="e11e7e4cd655b958296055f490ea8eadf5ea5ce7"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the plai-typed Racket package"
HOMEPAGE="https://github.com/mflatt/plai-typed"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
