# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="samth/fltest"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.09.21
	GH_COMMIT="8d2d686a7d940accf540b74a9409d3b51ea980eb"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the fltest Racket package"
HOMEPAGE="https://github.com/samth/fltest"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
