# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="florence/plot-bestfit"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.10.16
	GH_COMMIT="dd6ffbef2626d7cc7e6802389ce53d57d36bb21d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the plot-bestfit Racket package"
HOMEPAGE="https://github.com/florence/plot-bestfit"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
