# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="lexi-lambda/namespaced-transformer"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="4cdc1bdae09a07b78f23665267f2c7df4be5a7f6"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the namespaced-transformer Racket package"
HOMEPAGE="https://github.com/lexi-lambda/namespaced-transformer"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/namespaced-transformer-lib
	dev-racket/namespaced-transformer-doc
"
RDEPEND="${DEPEND}"

S="${S}/namespaced-transformer"
