# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="kisaragi-hiu/pangu.rkt"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.12.16
	GH_COMMIT="56c2d70132e0d756dc69f9777eb752ff989f5ede"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Paranoid text spacing with Racket."
HOMEPAGE="https://github.com/kisaragi-hiu/pangu.rkt"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
