# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mcdejonge/rs-l"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.06.06
	GH_COMMIT="43616cd03e53b0109826736b461086b7146ed971"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Library with loop and event tools for rs (the Racket Sequencer)"
HOMEPAGE="https://github.com/mcdejonge/rs-l"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rs
"
RDEPEND="${DEPEND}"
