# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="97jaz/gregor"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.02.26
	GH_COMMIT="91d71c6082fec4197aaf9ade57aceb148116c11c"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Documentation part of gregor library"
HOMEPAGE="https://github.com/97jaz/gregor"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/tzinfo
	dev-racket/gregor-lib
"
RDEPEND="${DEPEND}"

S="${S}/gregor-doc"
