# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="euhmeuh/web-galaxy"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.02.15
	GH_COMMIT="2d9d5710aec25d961dcfc37a2e88c3c0f435021f"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A minimalist web framework for the Racket web-server"
HOMEPAGE="https://github.com/euhmeuh/web-galaxy"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/web-galaxy-doc
	dev-racket/web-galaxy-lib
"
RDEPEND="${DEPEND}"

S="${S}/web-galaxy"
