# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="alex-hhh/geoid"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.11.16
	GH_COMMIT="eb04d4c736d4b17e4095dbba89e25cac3ab7ab60"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="work efficiently with geographic data"
HOMEPAGE="https://github.com/alex-hhh/geoid"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/al2-test-runner
"
RDEPEND="${DEPEND}"
