# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jsmaniac/debug-scopes"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.11
	GH_COMMIT="8d8f13976b634113f717ddbaf76e9de85203557c"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Some utilities which help debugging scope-related issues for unhygienic macros"
HOMEPAGE="https://github.com/jsmaniac/debug-scopes"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/scribble-enhanced
	dev-racket/reprovide-lang
	dev-racket/pretty-format
"
RDEPEND="${DEPEND}"
