# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="sanchom/pollen-citations-mcgill"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.31
	GH_COMMIT="4d510c4098e00e97257b50b6a9189d7e660c3c8c"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A McGill-style citations system that works within the Pollen publishing system."
HOMEPAGE="https://github.com/sanchom/pollen-citations-mcgill"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/txexpr
	dev-racket/pollen
"
RDEPEND="${DEPEND}"
