# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="bartbes/mosquitto-racket"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="03b969b3f8806f7cfeb31b281981628fe8e2ca8b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An FFI binding of libmosquitto for racket"
HOMEPAGE="https://github.com/bartbes/mosquitto-racket"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
