# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mbutterick/sugar"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.18
	GH_COMMIT="c90834b77afad07f9b02986fc8e157ccf30b753c"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="shortcuts for simplicity & readability"
HOMEPAGE="https://github.com/mbutterick/sugar"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
