# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="hkrish/irandom"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.17
	GH_COMMIT="f38e03c69fce7462b81106f567c32ce34f0ed830"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the irandom Racket package"
HOMEPAGE="https://github.com/hkrish/irandom"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
