# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="SimonLSchlee/layout-interactive"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.06.02
	GH_COMMIT="bf245c3ecbc2c93cc236fd27ea7b37bb8560eccd"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="interact utility for use with 'layout' library"
HOMEPAGE="https://github.com/SimonLSchlee/layout-interactive"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/layout
"
RDEPEND="${DEPEND}"
