# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="src_prepare/collector2"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.25
	GH_COMMIT="5a8331925b9837fc6e6a639cfce2e6e0b5aa1d6b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="generate Gentoo ebuild scripts from Racket catalog packages"
HOMEPAGE="https://gitlab.com/src_prepare/collector2"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
