# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="rmculpepper/asn1"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.11.26
	GH_COMMIT="3afe9706302fcc6763f8d61622dee83ab6fa0c26"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="ASN.1 library"
HOMEPAGE="https://github.com/rmculpepper/asn1"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/asn1-lib
"
RDEPEND="${DEPEND}"

S="${S}/asn1-test"
