# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/exact-decimal-lang"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="0aae96ff741748e3a7da4239ad748e56c5f49470"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="a lang-extension that reads decimals as exact rationals"
HOMEPAGE="https://github.com/AlexKnauth/exact-decimal-lang"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
