# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dedbox/racket-diagrams"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.07.10
	GH_COMMIT="ab990ea081e982f7216ed9f7ff3c8e44749cd645"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Draw technical diagrams"
HOMEPAGE="https://github.com/dedbox/racket-diagrams"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
