# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Bogdanp/mobilpay"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.06.27
	GH_COMMIT="0c75ab1a28c834035fb1d661e3e0390338b9f34a"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the mobilpay Racket package"
HOMEPAGE="https://github.com/Bogdanp/mobilpay"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/gregor-lib
	dev-racket/crypto-lib
"
RDEPEND="${DEPEND}"
