# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="stamourv/staged-slide"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="28b9389ea83984306dd50b634cb795c3bd86ca41"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Helpers for building staged slides in Slideshow"
HOMEPAGE="https://github.com/stamourv/staged-slide"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
