# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="lijunsong/pollen-rock"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.06.17
	GH_COMMIT="8107c7c1a1ca1e5ab125650f38002683b15b22c9"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An enhanced Pollen server and an in-browser editor for Pollen files"
HOMEPAGE="https://github.com/lijunsong/pollen-rock"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/sugar
	dev-racket/pollen
"
RDEPEND="${DEPEND}"
