# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Junker/routy"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.05.18
	GH_COMMIT="2c48b4649ee102c8f175cae59bf5eeb6d6a041c9"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Routy is a lightweight high performance HTTP request router for Racket."
HOMEPAGE="https://github.com/Junker/routy"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/response-ext
	dev-racket/racket-route-match
"
RDEPEND="${DEPEND}"
