# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Kalimehtar/fast-convert"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="2420aeb2ce8c7fb3e14d0ee1d560c33e16aa1b80"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Fast conversion from bytes to string  for one-byte encoding"
HOMEPAGE="https://github.com/Kalimehtar/fast-convert"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
