# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="car.margiotta/dice-parser"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.08
	GH_COMMIT="99f06659f3f7659dc577df4fef1d2b6f6eb12baa"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A parser for dice expressions like 1d6-1d4+5."
HOMEPAGE="https://gitlab.com/car.margiotta/dice-parser"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
