# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/defpat"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="b1ab923ef4c92355de7ee77703d8af692835c8f0"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="a version of define for defining functions with match-patterns as arguments"
HOMEPAGE="https://github.com/AlexKnauth/defpat"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/scribble-code-examples
	dev-racket/reprovide-lang
	dev-racket/sweet-exp
	dev-racket/generic-bind
"
RDEPEND="${DEPEND}"
