# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Metaxal/MrEd-Designer"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.06
	GH_COMMIT="f88e45905dc0fcb13fa327d9b39a47444384921e"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A WYSIWYG GUI generator for Racket"
HOMEPAGE="https://github.com/Metaxal/MrEd-Designer"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
