# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="stamourv/sexp-diff"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.03.09
	GH_COMMIT="5791264cb7031308b81c8c91df457cd51888210f"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Tests for sexp-diff-lib"
HOMEPAGE="https://github.com/stamourv/sexp-diff"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/sexp-diff-lib
"
RDEPEND="${DEPEND}"

S="${S}/sexp-diff-test"
