# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="ifigueroap/racket-quickcheck"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.07.13
	GH_COMMIT="902eb30fa8f5c0df7910df22c1442ff866b3920d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Quickcheck Clone"
HOMEPAGE="https://github.com/ifigueroap/racket-quickcheck"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/doc-coverage
"
RDEPEND="${DEPEND}"
