# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="lehitoskin/libtoxcore-racket"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="8baa14d6835ec4371de4ce7aa73237cd509d8f48"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A Racket wrapper for the Tox libraries."
HOMEPAGE="https://github.com/lehitoskin/libtoxcore-racket"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
