# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="willghatch/racket-udelim"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.03.09
	GH_COMMIT="58420f53c37e0bee451daa3dc5e2d72f7fc4d967"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Add more parens and string delimiters."
HOMEPAGE="https://github.com/willghatch/racket-udelim"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
