# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="tonyg/racket-ansi"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.02.18
	GH_COMMIT="c14081de59bc7273f1f9088a51d6d9c202b2b9d0"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="ANSI and VT10x escape sequences for Racket."
HOMEPAGE="https://github.com/tonyg/racket-ansi"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
