# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="lexi-lambda/racket-multimethod"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="8a0903ebaedd919971c382eeb785f05080c7a8d6"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the multimethod-lib Racket package"
HOMEPAGE="https://github.com/lexi-lambda/racket-multimethod"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rackunit-spec
"
RDEPEND="${DEPEND}"

S="${S}/multimethod-lib"
