# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/struct-like-struct-type-property"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.01.14
	GH_COMMIT="c961dbd9a5741895e838558bf19233fd4142e4d6"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Creating struct-type properties with a struct-like interface"
HOMEPAGE="https://github.com/AlexKnauth/struct-like-struct-type-property"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
