# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="soegaard/metapict"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.10.21
	GH_COMMIT="47ae265f73cbb92ff3e7bdd61e49f4af17597fdf"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Create beautiful pictures and diagrams"
HOMEPAGE="https://github.com/soegaard/metapict"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/racket-poppler
	dev-racket/graph-lib
	dev-racket/ppict
"
RDEPEND="${DEPEND}"
