# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mflatt/raco-cross"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.26
	GH_COMMIT="dbb94f2e039809d594cab4d6423509de10826e1e"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A raco command to drive cross compilation."
HOMEPAGE="https://github.com/mflatt/raco-cross"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
