# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="vishesh/racketscript"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.02
	GH_COMMIT="a424c694b2ee68f8daf722c1d56c75852841ac4e"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Goodies for RacketScript"
HOMEPAGE="https://github.com/vishesh/racketscript"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/racketscript-compiler
"
RDEPEND="${DEPEND}"

S="${S}/racketscript-extras"
