# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Bogdanp/racket-buid"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.04.05
	GH_COMMIT="5806054cbea5e69fae66a0b6d622752ace690afd"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Universally unique, lexicographically-sortable flake ids for Racket."
HOMEPAGE="https://github.com/Bogdanp/racket-buid"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rackcheck
"
RDEPEND="${DEPEND}"
