# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="basus/colophon"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.12.19
	GH_COMMIT="04989fbffb385a09d4f6b83ab9a132fa85ec8454"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An experimental static site generator"
HOMEPAGE="https://github.com/basus/colophon"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/pollen
"
RDEPEND="${DEPEND}"
