# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="codereport/racket-algorithms"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.07.24
	GH_COMMIT="b114ca74b632cd112d51509e79d2cf4f7aa55d2f"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the algorithms Racket package"
HOMEPAGE="https://github.com/codereport/racket-algorithms"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
