# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jbclements/simply-scheme"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.10.23
	GH_COMMIT="8b8ba2b50d8688c0db30a772c5eac7bb2f6400a7"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the simply-scheme Racket package"
HOMEPAGE="https://github.com/jbclements/simply-scheme"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
