# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dedbox/racket-graphics-engine"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.08.04
	GH_COMMIT="94d492f057e1fa712ceab1823afca31ffc80f04d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An accelerated graphics programming environment."
HOMEPAGE="https://github.com/dedbox/racket-graphics-engine"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/reprovide-lang-lib
	dev-racket/glsl
	dev-racket/glm
	dev-racket/opengl
"
RDEPEND="${DEPEND}"
