# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="pivot.cs.unb.ca"
GH_REPO="git/unb-cs2613"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.07.22
	GH_COMMIT="67576e2029d4865143c458b26fbc9da78c066a66"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Racket packages for UNB CS2613"
HOMEPAGE="https://pivot.cs.unb.ca/git/unb-cs2613"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/date
	dev-racket/explorer
	dev-racket/frog
"
RDEPEND="${DEPEND}"
