# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Lonero-Team/Racket-Package"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.12
	GH_COMMIT="292c4ba1da5499be8748bd11aeb3dd461b3ab6ff"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A package for building distributed computing projects"
HOMEPAGE="https://github.com/Lonero-Team/Racket-Package"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
