# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="LiberalArtist/libxml2-ffi"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.11.28
	GH_COMMIT="34f26243e8f35ae84f248e02dfbd7214ec2c619d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Racket bindings for libxml2"
HOMEPAGE="https://github.com/LiberalArtist/libxml2-ffi"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rackunit-spec
"
RDEPEND="${DEPEND}"
