# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="dstorrs/racket-dstorrs-libs"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.02.01
	GH_COMMIT="a48a10112e78f74e51a879ec9faf38e268a97697"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the handy Racket package"
HOMEPAGE="https://github.com/dstorrs/racket-dstorrs-libs"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/sxml
"
RDEPEND="${DEPEND}"
