# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/scribble-example"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.07.19
	GH_COMMIT="8ea8ae06d859b607fd3600a68a806513580e1867"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Deprecated. Use the built in scribble/example instead."
HOMEPAGE="https://github.com/jackfirth/scribble-example"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/doc-coverage
	dev-racket/fancy-app
	dev-racket/reprovide-lang-lib
	dev-racket/sweet-exp-lib
"
RDEPEND="${DEPEND}"
