# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="zyrolasting/natural-cli"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.05.06
	GH_COMMIT="c7abc38d025159128d446ca1a6314ab909ffe920"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Easily write large command-line interfaces (CLIs)"
HOMEPAGE="https://github.com/zyrolasting/natural-cli"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
