# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="rymaju/code-sync"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.11.11
	GH_COMMIT="feea02e2cc19088ba7ce5336b89b22044d5dafcf"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Fast Code Sharing for DrRacket"
HOMEPAGE="https://github.com/rymaju/code-sync"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rfc6455
"
RDEPEND="${DEPEND}"
