# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="stchang/dropbox/"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="fc978c6c2feca00a74c4e5f9f7213a55585abe68"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="SDK for Dropbox"
HOMEPAGE="https://github.com/stchang/dropbox/"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
