# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="zyrolasting/xiden"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.07.03
	GH_COMMIT="1065a55a11491bbd225a34b465f1862b2c2d63df"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Flexibly distributes software. Does not have the same limits as raco pkg."
HOMEPAGE="https://github.com/zyrolasting/xiden"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
