# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="zyrolasting/xiden"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.24
	GH_COMMIT="c5d42843350439613a8c92ad1bc4ff51ec224646"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Guix-like functional dependency manager"
HOMEPAGE="https://github.com/zyrolasting/xiden"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
