# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jsmaniac/dotlambda"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.04
	GH_COMMIT="96cfe93ab611db377a4a68f4b0a7e483ebf506a6"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the dotlambda Racket package"
HOMEPAGE="https://github.com/jsmaniac/dotlambda"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/debug-scopes
	dev-racket/chain-module-begin
	dev-racket/typed-map-lib
"
RDEPEND="${DEPEND}"
