# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="ralsei/graphite"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.09
	GH_COMMIT="2e353be9d3c7e727b6f28597e0f6d64a7c42ee63"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A ggplot2-inspired data visualization library (no documentation)"
HOMEPAGE="https://github.com/ralsei/graphite"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/simple-polynomial
	dev-racket/threading-lib
	dev-racket/loess
	dev-racket/fancy-app
	dev-racket/data-frame
	dev-racket/colormaps
"
RDEPEND="${DEPEND}"

S="${S}/graphite-lib"
