# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="takikawa/combinator-parser/"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="e64f938862f47f0e8bab8d6f406a8fa6a203e435"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the combinator-parser Racket package"
HOMEPAGE="https://github.com/takikawa/combinator-parser/"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
