# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="stchang/snappy"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="c97436037ff6600dc7df447a5aba3d59c3e7e011"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="FFI bindings to snappy, a fast compression library"
HOMEPAGE="https://github.com/stchang/snappy"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
