# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="takikawa/tr-pfds/"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.04.18
	GH_COMMIT="a08810bdfc760bb9ed68d08ea222a59135d9a203"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Purely functional data structures for Typed Racket"
HOMEPAGE="https://github.com/takikawa/tr-pfds/"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
