# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="robertkleffner/neologia"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.11.07
	GH_COMMIT="92d6ccde9041dc07b5c0db1849b4e1c65cb3cf2d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A language for creating and managing dictionaries and lexicons"
HOMEPAGE="https://github.com/robertkleffner/neologia"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/br-parser-tools-lib
	dev-racket/beautiful-racket-lib
	dev-racket/beautiful-racket
	dev-racket/brag
"
RDEPEND="${DEPEND}"
