# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="DexterLagan/cobalt2-theme"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.18
	GH_COMMIT="7782e2324b62cc496ca2167800a423c8929adf01"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="The Cobalt 2 color theme for DrRacket."
HOMEPAGE="https://github.com/DexterLagan/cobalt2-theme"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
