# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="samth/javascript.plt"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.04.22
	GH_COMMIT="327c2de5e09f885b682f80524ff3c12ef6c47543"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An implementation of JavaScript"
HOMEPAGE="https://github.com/samth/javascript.plt"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/in-new-directory
	dev-racket/pprint
	dev-racket/set
	dev-racket/parameter
"
RDEPEND="${DEPEND}"
