# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="BourgondAries/spipe"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.11.04
	GH_COMMIT="d6bc777a8113447fea9a3f10b5a0fbce6269dce4"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A 'super-pipe' that threads over Racket hash-tables"
HOMEPAGE="https://github.com/BourgondAries/spipe"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/threading
	dev-racket/nested-hash
"
RDEPEND="${DEPEND}"
