# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="zyrolasting/search-upward"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.10.11
	GH_COMMIT="02016d0ca3bdd76d69c9d376ae84936a63c5ca6e"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the search-upward Racket package"
HOMEPAGE="https://github.com/zyrolasting/search-upward"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
