# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="bksaiki/generic-flonum"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.20
	GH_COMMIT="eaf44e5099e3225806a39e2dbe5355ab809d41e9"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Alternative MPFR interface for emulating IEEE-754 floating-point numbers"
HOMEPAGE="https://github.com/bksaiki/generic-flonum"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
