# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Bogdanp/racket-forms"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.08.09
	GH_COMMIT="80e6dee1184ab4c435678bb3c45fa11bfabf56ee"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Web form validation (documentation only)."
HOMEPAGE="https://github.com/Bogdanp/racket-forms"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/forms-lib
"
RDEPEND="${DEPEND}"

S="${S}/forms-doc"
