# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="eu90h/stockfighter-racket"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="cf7669c2d79645a54ee287df14a3e704006e0096"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Stockfighter API client"
HOMEPAGE="https://github.com/eu90h/stockfighter-racket"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rfc6455
"
RDEPEND="${DEPEND}"
