# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="dustyweb/terminal-phase"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.08
	GH_COMMIT="ecf6f068c265de812d3decd003144ba4a2dd1e2b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Terminal Phase is a space shooter video game that runs in your terminal!"
HOMEPAGE="https://gitlab.com/dustyweb/terminal-phase"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/ansi
	dev-racket/raart
	dev-racket/pk
	dev-racket/goblins
	dev-racket/lux
"
RDEPEND="${DEPEND}"
