# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jsmaniac/anaphoric"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.11
	GH_COMMIT="2467143b69655d2db8685f3c4d7b19b94c93a409"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the anaphoric Racket package"
HOMEPAGE="https://github.com/jsmaniac/anaphoric"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
