# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jbclements/glpk"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.01.24
	GH_COMMIT="ff20adf1ea0f6792b6a858aa421c79ce22a8fd5d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="An interface to the Gnu Linear Programming Kit (GLPK)"
HOMEPAGE="https://github.com/jbclements/glpk"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/scribble-math
"
RDEPEND="${DEPEND}"
