# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Metaxal/global"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.12.03
	GH_COMMIT="d912b774228e449f19083cba15e37b188a1673b4"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Define global variables and automatically generate a command line parser."
HOMEPAGE="https://github.com/Metaxal/global"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/text-table
"
RDEPEND="${DEPEND}"
