# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="aptmcl/rosetta"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.09.15
	GH_COMMIT="38aeafd730f93edaec7474106e84dae6d8bc1261"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the rosetta Racket package"
HOMEPAGE="https://github.com/aptmcl/rosetta"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
