# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="macrotypefunctors/macrotypes-nonstx"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.05.03
	GH_COMMIT="b3f9839b6f8dcce4bf3fe9c15d5017214300924d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the macrotypes-nonstx Racket package"
HOMEPAGE="https://github.com/macrotypefunctors/macrotypes-nonstx"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/syntax-classes-lib
	dev-racket/agile
"
RDEPEND="${DEPEND}"
