# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="lexi-lambda/scripty"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="09a0e2fd24dfcd5942177d4a328821534ee60ded"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the scripty Racket package"
HOMEPAGE="https://github.com/lexi-lambda/scripty"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/scripty-lib
	dev-racket/scripty-doc
"
RDEPEND="${DEPEND}"

S="${S}/scripty"
