# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="stamourv/java-lexer"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="83e12122919d4582d63bea5b051cbeab6ee32c57"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Java syntax highlighting for Scribble."
HOMEPAGE="https://github.com/stamourv/java-lexer"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/profj
"
RDEPEND="${DEPEND}"
