# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="gitlab.com"
GH_REPO="racketeer/rktermios"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.08
	GH_COMMIT="cbcdd5b15542bf6f45907e6a6ba2932f0c4cd501"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the rktermios Racket package"
HOMEPAGE="https://gitlab.com/racketeer/rktermios"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
