# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="silver-ag/peony"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.07.01
	GH_COMMIT="cabbb94e5caf786004e9c54dd624fa4ec574998e"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A small frontend on web-server to make developing some kinds of webapp quicker."
HOMEPAGE="https://github.com/silver-ag/peony"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
