# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="m-hugi/nasa-open-api"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.06.22
	GH_COMMIT="aea1067af82aa4516f192e96bb987751ad2f6316"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Library for a handful of NASA's Open APIs"
HOMEPAGE="https://github.com/m-hugi/nasa-open-api"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
