# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/http2"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.05.31
	GH_COMMIT="aafdea48a4f1e6f8579531350aee3691f4060129"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A (wildly unimplemented) http2 client and server for Racket"
HOMEPAGE="https://github.com/jackfirth/http2"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rebellion
"
RDEPEND="${DEPEND}"
