# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mbutterick/describe"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.18
	GH_COMMIT="6489f1b499cbfcda74ced18555c5c2ca255921e5"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Doug Williams's 'describe' package from PLaneT"
HOMEPAGE="https://github.com/mbutterick/describe"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
