# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/twixt"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.02.20
	GH_COMMIT="41aca88a7a7e5a993460df011da67b4fa31daadc"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A library for modeling the board game TwixT"
HOMEPAGE="https://github.com/jackfirth/twixt"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rebellion
"
RDEPEND="${DEPEND}"
