# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="lotabout/axe"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="234c2d1f6849f3719c3fc3c2354a4d257e53943b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Handy utilities(macros/functions) for racket"
HOMEPAGE="https://github.com/lotabout/axe"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/scribble-code-examples
	dev-racket/collections
"
RDEPEND="${DEPEND}"
