# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/seq-no-order"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="dd9bc6956a2431f986d0b02aabcf61f5c91dc82f"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="~seq-no-order and ~no-order as pattern-expanders that work with syntax/parse."
HOMEPAGE="https://github.com/AlexKnauth/seq-no-order"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
