# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="zenspider/check-sexp-equal"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.07.01
	GH_COMMIT="59d1d837e8d7d6d0d4a8d4dc23497a9589f234fc"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A simple extension for rackunit that provides s-expression diffs on failure."
HOMEPAGE="https://github.com/zenspider/check-sexp-equal"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/sexp-diff
"
RDEPEND="${DEPEND}"
