# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="bitbucket.org"
GH_REPO="derend/andlet"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.05.15
	GH_COMMIT="2da90e6a47c2f87c57d05d9bd7bc221677d4b9d5"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Coupling and logic to let and let* forms."
HOMEPAGE="https://bitbucket.org/derend/andlet"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
