# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="LeifAndersen/racket-scratch"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.04.20
	GH_COMMIT="92ec687d248f7ce587589305611367512d2a0506"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the scratch Racket package"
HOMEPAGE="https://github.com/LeifAndersen/racket-scratch"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/with-cache
	dev-racket/reprovide-lang
"
RDEPEND="${DEPEND}"
