# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jeapostrophe/spvector"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="aba0ba4f4d8df27dc17252b984eca2f76f4ae414"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the spvector Racket package"
HOMEPAGE="https://github.com/jeapostrophe/spvector"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
