# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="SimonLSchlee/open-app"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.06.01
	GH_COMMIT="5503f0d2b5e398c864e6bdacfac9c672bf9b9869"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A utility for opening a file or url with the default application."
HOMEPAGE="https://github.com/SimonLSchlee/open-app"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
