# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="pivot.cs.unb.ca"
GH_REPO="git/unb-cs4613"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.01.12
	GH_COMMIT="2822b8c4d4864c79181608ae0e73d9f04c24f43c"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Handin client + metapackage for UNB Fredericton CS4613"
HOMEPAGE="https://pivot.cs.unb.ca/git/unb-cs4613"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/plai-dynamic
	dev-racket/brag
	dev-racket/plait
"
RDEPEND="${DEPEND}"
