# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="samth/raco-bug"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="21d5b6aa30e8efa33bf7110482dea48541399edb"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Submit bug reports"
HOMEPAGE="https://github.com/samth/raco-bug"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
