# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mcdejonge/rs"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.04.15
	GH_COMMIT="4ec05adf44019ff153e867612d3eeee7ea586082"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the rs Racket package"
HOMEPAGE="https://github.com/mcdejonge/rs"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rtmidi
"
RDEPEND="${DEPEND}"
