# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/define-match-spread-out"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="0f97b9f4bdee1655617f70f4291cf774993b2f83"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="a version of define that allows definitions to be spread across a file"
HOMEPAGE="https://github.com/AlexKnauth/define-match-spread-out"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/scribble-code-examples
	dev-racket/defpat
"
RDEPEND="${DEPEND}"
