# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="lexi-lambda/racket-tulip"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="1613cfd4d7e8dbc8ceb86cf33479375147f42b2f"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the tulip-test Racket package"
HOMEPAGE="https://github.com/lexi-lambda/racket-tulip"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/tulip-lib
"
RDEPEND="${DEPEND}"

S="${S}/tulip-test"
