# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="shhyou/drracket-scheme-dark-green"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.01.03
	GH_COMMIT="bda60667005f146ffa78b6435e10cd5731d7f211"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="This is a white-on-black dark green colorscheme for DrRacket."
HOMEPAGE="https://github.com/shhyou/drracket-scheme-dark-green"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
