# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jbclements/ragg"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.02.22
	GH_COMMIT="fe71542609bd707d4fd6d842d74c164ae2b2adff"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the ragg Racket package"
HOMEPAGE="https://github.com/jbclements/ragg"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/python-tokenizer
"
RDEPEND="${DEPEND}"
