# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="camoy/private-in"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.08.15
	GH_COMMIT="d8a8105a70c8940f6a156dc68d035abbcdd2fe08"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Require private bindings."
HOMEPAGE="https://github.com/camoy/private-in"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/chk-lib
"
RDEPEND="${DEPEND}"
