# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="johnstonskj/racket-locale"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.09.28
	GH_COMMIT="4381d42d76548b6b52522349955be55ee46e3700"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="More, and complete, locale tools."
HOMEPAGE="https://github.com/johnstonskj/racket-locale"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/cover-coveralls
	dev-racket/gregor-lib
"
RDEPEND="${DEPEND}"
