# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mordae/racket-tesira"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="47ae8cd92ad3b2610a3f95db9ba3e16db6b24d48"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Biamp Tesira Client Library"
HOMEPAGE="https://github.com/mordae/racket-tesira"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/mordae
"
RDEPEND="${DEPEND}"
