# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="leafac/pollen-component"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.05.13
	GH_COMMIT="36853a84a58e2889b0e3065d5f1357a596e3c1e6"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Component-based development for Pollen"
HOMEPAGE="https://github.com/leafac/pollen-component"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/sugar
	dev-racket/pollen
"
RDEPEND="${DEPEND}"
