# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="philnguyen/z3-rkt"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.05.11
	GH_COMMIT="78deda2c7a377b93caefd40fd16e5df9c6d53c40"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Z3 bindings for Racket"
HOMEPAGE="https://github.com/philnguyen/z3-rkt"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

S="${S}/z3/"
