# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="Kalimehtar/free-gettext"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.10.03
	GH_COMMIT="fd00d769a9cce03bb8675ee62299c878b9c0d5bb"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="GNU gettext compatible library for internationalization with BSD license"
HOMEPAGE="https://github.com/Kalimehtar/free-gettext"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
