# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="greghendershott/flexpr"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="a547ca94094a2090f12b0028b634da0b08d42df8"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Expressions rendered as both XML and JSON"
HOMEPAGE="https://github.com/greghendershott/flexpr"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
