# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="leafac/css-expr"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.05.12
	GH_COMMIT="d060b2a76d08013c91318890dc5d9f6cc6c81138"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="S-expression-based CSS"
HOMEPAGE="https://github.com/leafac/css-expr"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/nanopass
"
RDEPEND="${DEPEND}"
