# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="racket/racket-lang-org"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.07.01
	GH_COMMIT="b73ba0e15a644b77db8fcbcab775c50a020c6c85"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Sources for http://racket-lang.org"
HOMEPAGE="https://github.com/racket/racket-lang-org"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/s3-sync
	dev-racket/ppict
	dev-racket/frog
	dev-racket/gregor-lib
	dev-racket/txexpr
	dev-racket/sugar
	dev-racket/css-tools
	dev-racket/pollen
	dev-racket/graph
"
RDEPEND="${DEPEND}"
