# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="takikawa/raco-find-collection"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="00f0d3dbad025fdb98d23b9ee1a78731f460d541"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A script to find collections."
HOMEPAGE="https://github.com/takikawa/raco-find-collection"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
