# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/turn-based-game"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.01.19
	GH_COMMIT="bdc793d50f67bb59446caecc9e5771d84e1eba17"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="interfaces and tools for defining and playing turn-based games"
HOMEPAGE="https://github.com/AlexKnauth/turn-based-game"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/collections-doc
	dev-racket/collections-lib
	dev-racket/agile
"
RDEPEND="${DEPEND}"
