# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="bennn/gtp-util"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.02.17
	GH_COMMIT="e1c3d7b4ed1128271324201171240e111ce51419"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="37 helper functions you won't find anywhere else"
HOMEPAGE="https://github.com/bennn/gtp-util"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rackunit-abbrevs
"
RDEPEND="${DEPEND}"
