# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="parnikkapore/rkt-boincrpc"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.25
	GH_COMMIT="f05dc275c2dac7196b65058f26af9ca9e074aef6"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the boincrpc Racket package"
HOMEPAGE="https://github.com/parnikkapore/rkt-boincrpc"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/libquiche
"
RDEPEND="${DEPEND}"
