# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="eu90h/mockfighter"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="63906eff874e90644725dbff5365889d959e2294"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Stockfighter-like API for a limit order exchange"
HOMEPAGE="https://github.com/eu90h/mockfighter"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/stockfighter-racket
"
RDEPEND="${DEPEND}"
