# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="oetr/racket-hdf5"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.12.11
	GH_COMMIT="5836fc438ee36f94c80362b7da79b252a6429009"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="FFI bindings to the hdf5 library"
HOMEPAGE="https://github.com/oetr/racket-hdf5"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
