# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jbclements/portaudio"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.08.04
	GH_COMMIT="74dfaf1d6317a9f5479ae5492e874e9e73888a46"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Bindings for portaudio, a cross-platform audio library."
HOMEPAGE="https://github.com/jbclements/portaudio"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
