# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="bennn/racket-left-pad"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.02.23
	GH_COMMIT="2b17c398c033cc0cbf3535144860676ca682027d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="String left pad"
HOMEPAGE="https://github.com/bennn/racket-left-pad"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
