# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="samth/gradual-typing-bib"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.02.01
	GH_COMMIT="63567f8f380ca2bc908ec11d9f9c7d856b8ab3bf"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the gradual-typing-bib Racket package"
HOMEPAGE="https://github.com/samth/gradual-typing-bib"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
