# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="samth/gradual-typing-bib"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.10
	GH_COMMIT="4c73669423a6877f37244e2015a0b02c8878f425"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the gradual-typing-bib Racket package"
HOMEPAGE="https://github.com/samth/gradual-typing-bib"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
