# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="mflatt/uu-cs3520"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.08.04
	GH_COMMIT="b0dfad48eab5d41706b6016bdfc6b9acafe46093"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Utah CS 3520 homework submission plugin for DrRacket"
HOMEPAGE="https://github.com/mflatt/uu-cs3520"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/plait
"
RDEPEND="${DEPEND}"
