# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="rmculpepper/ppict"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2018.10.18
	GH_COMMIT="5d2d5f9d0a10f0988c7ed1f1986a0a6a15dcdb77"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="progressive picts and slideshows"
HOMEPAGE="https://github.com/rmculpepper/ppict"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
