# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="GThad/g-code-tools"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.08.04
	GH_COMMIT="8a786ec0608afdc0729c344e7cd58d368fc86ff9"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A collection of tools for manipulating G-code."
HOMEPAGE="https://github.com/GThad/g-code-tools"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
