# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jackfirth/planning"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.06.05
	GH_COMMIT="b880f85effd4520e14b815d1dbe0ff7e71f4aaf8"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A library for automated planning."
HOMEPAGE="https://github.com/jackfirth/planning"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/rebellion
	dev-racket/point-free
	dev-racket/fancy-app
	dev-racket/chess
"
RDEPEND="${DEPEND}"
