# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="AlexKnauth/typed-racket-datatype"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.07.23
	GH_COMMIT="dc955052081b18a164552c4e7db75ac392a92402"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Algebraic Datatypes for Typed Racket (implementation)"
HOMEPAGE="https://github.com/AlexKnauth/typed-racket-datatype"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/syntax-classes-lib
"
RDEPEND="${DEPEND}"

S="${S}/typed-racket-datatype-lib"
