# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="takikawa/racket-cpu-affinity"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="bc6316cbc7bc3f2179ae569bfe7c23a53b62025f"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A library for getting/setting CPU affinity"
HOMEPAGE="https://github.com/takikawa/racket-cpu-affinity"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
