# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="eutro/scheme2d"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.07
	GH_COMMIT="65b4a3c69d8c13fbcfc542fa366409fecc1089f4"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="The future of programming."
HOMEPAGE="https://github.com/eutro/scheme2d"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
