# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="rmculpepper/iracket"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.03.05
	GH_COMMIT="9af0e87d61565a9ecb41119c481e7e36c0c5287d"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Jupyter kernel for Racket"
HOMEPAGE="https://github.com/rmculpepper/iracket"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/sha
	dev-racket/uuid
	dev-racket/zeromq-r-lib
"
RDEPEND="${DEPEND}"
