# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="samth/lang-slide"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.08.14
	GH_COMMIT="ea86af49c3d7fe2fe0e80c1c9488b3447a0efbdd"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A picture showing all the languages used to implement Racket."
HOMEPAGE="https://github.com/samth/lang-slide"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
