# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="git.sr.ht"
GH_REPO="~sschwarzer/todo-txt"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.06.11
	GH_COMMIT="7cc4f178f23381c72a49fc5397f84033eb2fddcd"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the todo-txt Racket package"
HOMEPAGE="https://git.sr.ht/~sschwarzer/todo-txt"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
