# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="sorawee/stream-values"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.12.12
	GH_COMMIT="a5e107f20b8794dc3b3bf6b9402ec1aa7af30c8b"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A library for multiple values manipulation in streams"
HOMEPAGE="https://github.com/sorawee/stream-values"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
