# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="LeifAndersen/racket-_"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2017.08.15
	GH_COMMIT="e687a8eaf4ef62b97ad5d37f6fd09cb684c7d101"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="the _ Racket package"
HOMEPAGE="https://github.com/LeifAndersen/racket-_"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
