# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="emsenn/qtops"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.10.04
	GH_COMMIT="ef9950feed1435514911f731303c6e4fd4198ca6"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Perform operations on things with qualities"
HOMEPAGE="https://github.com/emsenn/qtops"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
