# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="jeapostrophe/mode-lambda"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2019.11.29
	GH_COMMIT="64b5ae81f457ded7664458cd9935ce7d3ebfc449"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="2d sprite-based graphics engine"
HOMEPAGE="https://github.com/jeapostrophe/mode-lambda"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"

DEPEND="
	dev-racket/opengl
	dev-racket/reprovide-lang-lib
	dev-racket/lux
"
RDEPEND="${DEPEND}"
