# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="tjitze/ranked-programming"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2020.05.18
	GH_COMMIT="5503146a8ac9779d949905b778f0d9fd6d8c0d1a"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="A library that provides ranked programming functionality in Racket."
HOMEPAGE="https://github.com/tjitze/ranked-programming"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
