# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Initial ebuild generated by collector2
# https://gitlab.com/src_prepare/collector2

EAPI=7

GH_DOM="github.com"
GH_REPO="alex-hhh/plot-container"

if [[ "${PV}" != *99999999* ]]; then
	# version: 2021.03.03
	GH_COMMIT="9bfdc610c1e2677506baa66df576c3ec03ac1a84"
	KEYWORDS="~amd64"
fi

inherit gh racket

DESCRIPTION="Embed plot snips in Racket GUI applications"
HOMEPAGE="https://github.com/alex-hhh/plot-container"

RESTRICT="mirror"
LICENSE="all-rights-reserved"
SLOT="0"
